### ISSUE TITLE
Problems adding custom control in component

### ISSUE THREAD

**Issue by MarcoLeko** [bluehalo/ngx-leaflet#106]
I have difficulties to add a custom control on my map. I put this question with the regarding code on stakeoverflow([https://stackoverflow.com/questions/47608576/leaflet-customcontrol-angular-2]), but since know one there is able to answer the question, i try it here. (This could definitly be added on the README.md)

Best regards

**Comment by reblace** [comment]
I added the ngx-leaflet tag in SO and added a comment.

**Comment by MarcoLeko** [comment]
appreciate the fast respond, thanks!

**Comment by reblace** [comment]
Following up in SO, gonna close this.
