### ISSUE TITLE
Angular 4 NG CLI Can't bind to 'leafletOptions' since it isn't a known property of 'div'

### ISSUE THREAD

**Issue by hackerunet** [bluehalo/ngx-leaflet#107]
No matter what I import or how the [leafletOptions] is not recognized by angular.
I got an error trying to use it
Can't bind to 'leafletOptions' since it isn't a known property of 'div'

**Comment by kylecordes** [comment]
I think we hit this exact same situation. If you are having the same thing we did, here is the solution. In your top level (app) module, do this is shown in the documentation:

```
imports: [
    ...
    LeafletModule.forRoot()
]
```

Then in the module where you are using the leaflet directive:

```
imports: [
    ...
    LeafletModule
]
```

The first thing is to make sure the right things are "provided" application wide. The second thing is to make sure the directive is available in the module where you use it.

**Comment by hackerunet** [comment]
I have it already declared in my app.module.ts and I'm trying to use it in a component called TrackingComponent, here is the code:
app.module.ts
```
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { LocationStrategy, HashLocationStrategy } from '@angular/common';

import { AppComponent } from './app.component';
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';
import { TabsModule } from 'ngx-bootstrap/tabs';
import { NAV_DROPDOWN_DIRECTIVES } from './shared/nav-dropdown.directive';

import { ChartsModule } from 'ng2-charts/ng2-charts';
import { SIDEBAR_TOGGLE_DIRECTIVES } from './shared/sidebar.directive';
import { AsideToggleDirective } from './shared/aside.directive';
import { BreadcrumbsComponent } from './shared/breadcrumb.component';

// Routing Module
import { AppRoutingModule } from './app.routing';

// Layouts
import { FullLayoutComponent } from './layouts/full-layout.component';
import { SimpleLayoutComponent } from './layouts/simple-layout.component';
import { LeafletModule } from '@asymmetrik/ngx-leaflet';

@NgModule({
  imports: [
    BrowserModule,
    AppRoutingModule,
    BsDropdownModule.forRoot(),
    TabsModule.forRoot(),
    ChartsModule,
    LeafletModule.forRoot()
  ],
  declarations: [
    AppComponent,
    FullLayoutComponent,
    SimpleLayoutComponent,
    NAV_DROPDOWN_DIRECTIVES,
    BreadcrumbsComponent,
    SIDEBAR_TOGGLE_DIRECTIVES,
    AsideToggleDirective
  ],
  providers: [{
    provide: LocationStrategy,
    useClass: HashLocationStrategy
  }],
  bootstrap: [ AppComponent ]
})
export class AppModule { }

```

tracking.component.ts
```
import { Component, OnInit } from '@angular/core';
import * as L from 'leaflet';
import { latLng, tileLayer } from 'leaflet';

@Component({
  selector: 'app-tracking',
  templateUrl: './tracking.component.html',
  styleUrls: ['./tracking.component.scss']
})
export class TrackingComponent {

  private map: L.Map;

  options = {
    layers: [
      L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 15 })
    ],
    zoom: 4,
    center: L.latLng([39.878868, -100.357010])
  };

  constructor() {
    console.log("loading tracking");
  }

  onMapReady(map: L.Map) {
    this.map = map;
  }
}
```

**Comment by hackerunet** [comment]
hey I forgot to add it into my component.module.ts it worked!!
thanks

**Comment by kylecordes** [comment]
@hackerunet Excellent. It seems like this is a weakness in the documentation.

**Comment by reblace** [comment]
The ngx-leaflet docs assume you will also be referring to the Angular.io docs. In this case, importing into subcomponents is not specific to ngx-leaflet, so it isn't covered in our README.

Most of the config stuff that's redundant w/Angular.io docs is just "quick start" stuff. But, it's admittedly a subjective judgement call.

**Comment by reblace** [comment]
I added a couple lines to the README highlighting the fact that the user might need to also import the Leaflet module into their module and referring them to the Angular.io docs. It'll get merged into the next release. Gonna close this cause I am assuming the issue was addressed. Thanks!
