### ISSUE TITLE
how to custom/remove prefix in tileLayer attribution?

### ISSUE THREAD

**Issue by sgrillon14** [bluehalo/ngx-leaflet#117]
```
LAYER_OCM = {
    id: 'opencyclemap',
    name: 'Open Cycle Map',
    enabled: true,
    layer: tileLayer('http://{s}.tile.opencyclemap.org/cycle/{z}/{x}/{y}.png', {
        maxZoom: 18,
        attribution: 'Open Cycle Map'
    })
};
```

Official docs:

[http://leafletjs.com/reference-1.0.0.html#map-attributioncontrol](http://leafletjs.com/reference-1.0.0.html#map-attributioncontrol)

![2018-01-02_162848](https://user-images.githubusercontent.com/5530550/34488834-4143b904-efda-11e7-9d22-3b2c1c7176e8.png)

![2018-01-02_163406](https://user-images.githubusercontent.com/5530550/34489124-41ee4bfc-efdb-11e7-8095-56e56f08217f.png)

**Comment by reblace** [comment]
The ngx-leaflet plugin doesn't affect this. You should look at Leaflet itself for this.
But, I wouldn't be surprised if they don't allow you to get rid of it.

**Comment by alexgoldstone** [comment]
This is what I do:
```
ngOnInit() {
    this.options = {
        layers: [
            tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
                maxZoom: 18,
                attribution:
                    'My attribution <a href="http://test.com" target="_blank">My Link</a>'
            })
        ],
        zoom: 5,
        center: latLng(46.879966, -121.726909),
        attributionControl: false
    };
}

onMapReady(map: Map) {
    this.map = map;
    this.map.addControl(
        control.attribution({
            position: 'bottomright',
            prefix: ''
        })
    );
}
```

**Comment by sgrillon14** [comment]
This solution ready, thanks @alexgoldstone 

```
  (leafletMapReady)="onMapReady($event);"
  [leafletOptions]="options"


  import { Layer, tileLayer, Map, control } from 'leaflet';
  ...
  options: any = {};
  constructor() {
    this.options['attributionControl'] = false;
  }
  ...
  onMapReady(map: Map) {
    map.addControl(
        control.attribution({
            position: 'bottomright',
            prefix: ''
        })
    );
  }
```
    
![2018-01-03_204117](https://user-images.githubusercontent.com/5530550/34536791-96d1bf64-f0c6-11e7-9648-7952de22b2d5.png)

**Comment by orange-beans** [comment]
Put the following code:
`document.getElementsByClassName( 'leaflet-control-attribution' )[0].style.fontSize = '0px';`

**Comment by antoine4ucsd** [comment]
hello , any suggestion to do the same in R environment? thank you
