### ISSUE TITLE
Delete/wipe overlays with event

### ISSUE THREAD

**Issue by crooksey** [bluehalo/ngx-leaflet#119]
So I am using this plugin (perfectly), how I use it.

I for example, 4 arrays, each containing lat/lng pairs.

I then have 4 overlays, to draw each array on the leaflet map as a polyline. (this works fine).

Say for example I add on two of these overlays, then make changes to my data, if I forget to "unshow" these two overlays, when I rebuild my overlays, although none are ticked to render on my map, they still shown as been drawn, e.g.

![screenshot_2018-01-08_15-49-29](https://user-images.githubusercontent.com/862603/34678770-ff941ac4-f48b-11e7-9f4e-cc0e5155532f.png)

Is there a way I can delete all drawings on the basemap, or "reset" it to its default state, currently my ngx-leaflet setup is below:
```typescript
polylineOverlay = []
this.layersControl = {
      overlays: this.polylineOverlay // placeholder to be populated by function
    };
    this.options = {
      layers: [
        tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '...' })
      ],
      zoom: 8,
      center: latLng(51.0, -0.761999)
    };

buildPolylines() {
    // HERE IS WHERE I NEED TO UNDRAW/CLEAR all markers/polylines
    this.polylineOverlay = [];
    this.layersControl = {
      overlays: this.polylineOverlay
    }; // the above code re-sets all current overlays
    // now build new polyline data
    polyLineArray = []
    for (const drop of drops) {
        const newLatLngPair: LatLngExpression = [drop.lat, drop.lng];
        polyLineArray.push(newLatLngPair);
        }
    this.polylineOverlay['Some Title] = polyline(polyLineArray, {color: colourChoice});
}
```
Then in my template I simply do:
```javascript
<div style="height: 600px;"
            leaflet
            [leafletLayersControl]="layersControl"
            [leafletOptions]="options">
        </div>
``` 
What would be the best way to achieve the above?

**Comment by crooksey** [comment]
So after looking more into the leaflet documentation, there does seem to be a method that exists to perform the above:

https://github.com/Leaflet/Leaflet/issues/3238

I can't access the leaflet site at the moment as its currently down.

Is there anyway I can call any of these, using ngx-leaflet, if using leaflet directly, I would define the map in my component, and could call these functions there, but as I am only defining the map in my template, how do I access it in my components to call these clear functions?

**Comment by crooksey** [comment]
Looking further I can see I can import a Map object directly:
```typescript
import {Map } from 'leaflet'
leafletMap: Map;
```

Then I *could* do:
```typescript
for (const layerKey of this.polyLineKeys) {
      const layerObject = this.polylineOverlay[layerKey];
      this.leafletMap.removeControl(layerObject);
    }
```

But this throws an error, can I import the map object directly as above and then render this in my template, if so how? Hopefully I am on the right track, but I could be no-where close, I will leave this as is for now, with the hope someone can point me in the right direction :)

**Comment by reblace** [comment]
You probably want to use the (leafletMapReady) output binding to get a handle to the map instance. That allows you to directly manipulate the underlying map instance. Check out the README for details.

**Comment by crooksey** [comment]
Thanks, I did as the example:

```typescript
import {Map } from 'leaflet'
leafletMap: Map;
onMapReady(map: Map) {
    // assing map to a variable that we can manipulate
    this.leafletMap = map;
 }
```
Then I can do:
```typescript
buildPolylines() {
   // START EXAMPLE CODE
    for (const layerKey of this.polyLineKeys) {
      const layerObject = this.polylineOverlay[layerKey];
      this.leafletMap.removeControl(layerObject);
    }
   // END EXAMPLE CODE
    this.polylineOverlay = [];
    this.layersControl = {
      overlays: this.polylineOverlay
    }; // the above code re-sets all current overlays
    // now build new polyline data
    polyLineArray = []
    for (const drop of drops) {
        const newLatLngPair: LatLngExpression = [drop.lat, drop.lng];
        polyLineArray.push(newLatLngPair);
        }
    this.polyLineKeys.push('Some Title');
    this.polylineOverlay['Some Title] = polyline(polyLineArray, {color: colourChoice});
}
```
