### ISSUE TITLE
How to use external js lib (leaflet.browser.print) in ngx-leaflet? 

### ISSUE THREAD

**Issue by sgrillon14** [bluehalo/ngx-leaflet#121]
Hello,

I'm trying to integrate [leaflet.browser.print](https://github.com/Igor-Vladyka/leaflet.browser.print) plugin in an Angular (with your ngx-leaflet)

I try add js file and use =>

Refer the scripts inside the angular-cli.json file:
```
"scripts": [
    ""../node_modules/leaflet.browser.print/src/leaflet.browser.print.js"" 
 ];
```

then add in typings.d.ts:
`declare module 'leaflet.browser.print/src/leaflet.browser.print';`

Import it in my component file as:
`import * as leafletbrowserprint from 'leaflet.browser.print/src/leaflet.browser.print';`

```
onMapReady(map: Map) {
    leafletbrowserprint.L.browserPrint().addTo(map);
}
```

Same question [here](https://github.com/Igor-Vladyka/leaflet.browser.print/issues/15)

**Comment by sgrillon14** [comment]
other solution/question => is it possible to create a  custom Control in ngx-leaflet?

```
var ourCustomControl = L.Control.extend({
 
  options: {
    position: 'topleft' 
    //control position - allowed: 'topleft', 'topright', 'bottomleft', 'bottomright'
  },
 
  onAdd: function (map) {
    return container;
  },
 
});
```

in @types\leaflet\index.d.ts:

```
export class Class {
    static extend(props: any): any/* how to return constructor of self extended type ? */;
```

Javascript example: http://www.coffeegnome.net/control-button-leaflet/

**Comment by sgrillon14** [comment]
problem solve by this PR: https://github.com/Igor-Vladyka/leaflet.browser.print/pull/17

**Comment by reblace** [comment]
Yeah, the 3rd party integration tutorial referenced in the README shows a bunch of examples of how to deal with integrating third party things (which is very similar to adding a custom control).

**Comment by sgrillon14** [comment]
leaflet.browser.print integration tutorial [here](https://github.com/Asymmetrik/ngx-leaflet-tutorial-plugins/pull/1)
