### ISSUE TITLE
leafletZoomOptions with zoomInTitle

### ISSUE THREAD

**Issue by sgrillon14** [bluehalo/ngx-leaflet#122]
I want translate in french "zoom out" and "Zoom in"

**html:**

`[leafletZoomOptions]="zoomOptions"`

**ts:**

```
options: any = {};
zoomOptions: any = {};

constructor(private mapService: MapService) {
    this.options['attributionControl'] = false;
    this.zoomOptions['zoomInTitle'] = 'Zoomer';
    this.zoomOptions['zoomOutTitle'] = 'Dézoomer';
}
```

![image](https://user-images.githubusercontent.com/5530550/35157774-47de769c-fd35-11e7-9543-c02e944781db.png)

Official documentation [here](http://leafletjs.com/reference-1.0.0.html):

Option | Type | Default | Description
-- | -- | -- | --
zoomInText | String | '+' | The text set on the 'zoom in' button.
zoomInTitle | String | 'Zoom in' | The title set on the 'zoom in' button.
zoomOutText | String | '-' | The text set on the 'zoom out' button.
zoomOutTitle | String | 'Zoom out' | The title set on the 'zoom out' button.

**Comment by sgrillon14** [comment]
Workaround but without using the `leafletZoomOptions` parameter of the directive:

```
constructor(private mapService: MapService) {
    this.options['attributionControl'] = false;
    this.options['zoomControl'] = false;
}
onMapReady(map: Map) {
    map.addControl(L.control.zoom({ position: 'topleft', zoomInTitle: 'Zoomer', zoomOutTitle: 'Dézoomer' }));
}
```

**Comment by reblace** [comment]
The expected way you'd deal with this is to turn off the default zoom control in the options, and then manually add a zoom control to the map with your options. The zoom options are ignored in Leaflet. It isn't ngx-leaflet doing that.

So, your way is more or less the correct way to deal with this.

**Comment by reblace** [comment]
Gonna close this since I assume your issue is addressed and this is the "right" way to address it.

**Comment by sgrillon14** [comment]
is it possible to use `[leafletZoomOptions]="zoomOptions"` ?  same question for `slice`?

**Comment by reblace** [comment]
ngx-leaflet uses those options as the second argument to zoom calls that are made as a result of binding to ```[leafletZoom]```. So, they wouldn't have the same effect that you're expecting.
