### ISSUE TITLE
getting geojson via http 

### ISSUE THREAD

**Issue by mdaly001** [bluehalo/ngx-leaflet#125]
Was hoping someone had experience grabbing the geojson and adding it to the map via httpClient. I have a mongodb running off node that I can get the data from. Just having trouble getting it from api to map

**Comment by reblace** [comment]
This is the relevant part of the leaflet docs: http://leafletjs.com/reference-1.3.0.html#geojson

You just need to follow the directions to create a geoJson layer and then add it to the layers array that you have bound to the map.

E.g.,
```
// Assume data is geoJson from your server (formatted according to the docs)
let geoJson = L.geoJSON(data);
this.layers.push(geoJson);
```

**Comment by mdaly001** [comment]
awesome thank you. will try this and see if i can grab it

**Comment by reblace** [comment]
There’s also an example in the demo: https://github.com/Asymmetrik/ngx-leaflet/blob/master/src/demo/app/leaflet/layers/layers-demo.component.ts

See the README for instructions on how to run the demo.

**Comment by mdaly001** [comment]
Thank you very much for sharing. Closing the issue.
