### ISSUE TITLE
Options from API section

### ISSUE THREAD

**Issue by gabomgp** [bluehalo/ngx-leaflet#126]
First, thanks for this useful component.

Second,

I reading the [Readme](https://github.com/Asymmetrik/ngx-leaflet#api) and i don't understand the many options in the API section. The options that i don't understand are:

* leafletPanOptions
* leafletZoomOptions
* leafletZoomPanOptions
* leafletFitBoundsOptions

So, the options are described in short paragraphs with links to Leaflet's docs, but the links don't show documentation. They show the main page of Leaflet. So, does exists documentation about that options?

**Comment by reblace** [comment]
The options are described in the leaflet docs. Here's the relevant direct links into the 1.3.x docs:

http://leafletjs.com/reference-1.3.0.html#pan-options
http://leafletjs.com/reference-1.3.0.html#zoom-options
http://leafletjs.com/reference-1.3.0.html#zoom/pan-options
http://leafletjs.com/reference-1.3.0.html#fitbounds-options

When you configure these options, they are used as the default options for all subsequent calls to zoom, pan, and fitBounds.

**Comment by reblace** [comment]
Gonna close this. If there are any other issues, let us know. Thanks!
