### ISSUE TITLE
Get marker lat lng after it is added

### ISSUE THREAD

**Issue by lucifer-AM** [bluehalo/ngx-leaflet#127]
Hi @reblace Please help.

Currently I have multiple maps on one screen. The number of maps could vary according to the maps that user adds dynamically.

Now the problem that I am facing here is how to identify the map on which the user is placing a marker.

------Also----------

How can we get the latitude and longitude of a marker after it is added?

**Comment by reblace** [comment]
Is the issue specifically that you have handlers that are shared across the map instances and you need to keep it straight which map is which in the handlers?

If you provide some sample code I can be more specific, but here's how I normally handle this (using the ngx-leaflet-tutorial-ngcli as the starting point):

app.component.ts:
```
import { Component } from '@angular/core';

import {icon, latLng, Layer, Map, MapOptions, marker, point, polyline, tileLayer} from 'leaflet';

export interface IMapSpec {
  map: Map;
  layers: Layer[];
  options: MapOptions;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  maps: IMapSpec[] = [];

  addMap() {
    this.maps.push({
      map: null,
      layers: [],
      options: {
        layers: [ tileLayer('http://{s}.google.com/vt/lyrs=m&x={x}&y={y}&z={z}',
                  { maxZoom: 20, subdomains: ['mt0', 'mt1', 'mt2', 'mt3'], detectRetina: true }) ],
        zoom: 7,
        center: latLng([ 46.879966, -121.726909 ])
      }
    });
  }

  onMapReady(map: Map, mapSpec: IMapSpec, i: number) {
    mapSpec.map = map;
  }

  addMarker(mapSpec: IMapSpec, i: number) {
    const newMarker = marker(
      [ 46.879966 + 0.1 * (Math.random() - 0.5), -121.726909 + 0.1 * (Math.random() - 0.5) ],
      {
        icon: icon({
          iconSize: [ 25, 41 ],
          iconAnchor: [ 13, 41 ],
          iconUrl: 'leaflet/marker-icon.png',
          shadowUrl: 'leaflet/marker-shadow.png'
        })
      }
    );

    mapSpec.layers.push(newMarker);
  }
}
```

app.component.html
```
<div><button (click)="addMap()">Add Map!</button></div>

<div class="map-tile" *ngFor="let m of maps; let i = index">

  <div class="map"
    leaflet
    (leafletMapReady)="onMapReady($event, m, i)"
    [leafletOptions]="m.options"
    [leafletLayers]="m.layers"></div>

  <button (click)="addMarker(m, i)">Add Marker!</button>

</div>
```

app.component.css:
```
.map {
  height: 200px;
  width: 200px;
}

.map-tile {
  margin: 12px;
  padding: 24px;
  float: left;
  border: 1px solid black;
}
```

What you're doing is storing all the context for each map separately and then passing the index and/or the actual map spec to the handler functions. That way you can keep everything separate. 

Also, you should be able to get the lat/long directly from the marker objects themselves, which are in the layers array in this case.

**Comment by lucifer-AM** [comment]
Ok @reblace thank you very much. That was the issue that I was facing. Now I have created the map array and I am initializing the map according to above. It works fine
