### ISSUE TITLE
L.extend does not exist on type

### ISSUE THREAD

**Issue by AndreasSchmid1** [bluehalo/ngx-leaflet#132]
I tried to implement an extended CRS.Simple with custom scale.

I had to use "(L as any).extend" because "L.extend" was not working. 

Can this be caused by missing typings?

**Comment by reblace** [comment]
I don't think there's an extend function that is directly accessible off of the ```L``` namespace. You would want to extend a class/interface like ```L.Layer``` or ```L.Evented```

**Comment by AndreasSchmid1** [comment]
Thx @reblace for the fast answer. I was trying to implement a custom crs described in this article 

https://gis.stackexchange.com/questions/200865/leaflet-crs-simple-custom-scale

It is already two years old so the Lextend is maybe obsolete now.

I thought it is some missing typing. If not, I apologize for my mistake and the case can be closed

**Comment by reblace** [comment]
http://leafletjs.com/reference-1.3.0.html#util

I think L.Util.extend is what you're looking for I think. Might have changed between Leaflet 0.7.x and 1.x

**Comment by AndreasSchmid1** [comment]
Thank you
