### ISSUE TITLE
How do implement a search functionality on the map

### ISSUE THREAD

**Issue by kue-bano** [bluehalo/ngx-leaflet#134]
Hi,
I want to implement a search function on the Map, where i can pass in an address and then the map is supposed to navigate to the location on the map. Is it possible to achieve this?

**Comment by alexgoldstone** [comment]
Hi @Slim-dev 

You will need to use an external **geocoding** service which will return latitude and longitude values for a specified address. 

For some, Goecoding would be considered outside the scope of Leaflet itself as there are many services that provide APIs you would utilise independently and then just utilise the resulting coordinates with Leaflet as required.

However there are also Leaflet specific plugins relating to this:

http://leafletjs.com/plugins.html#geocoding

**Comment by reblace** [comment]
Going to close this as I believe the question has been answered.
