### ISSUE TITLE
TypeError: Cannot read property 'project' of undefined

### ISSUE THREAD

**Issue by razfazz** [bluehalo/ngx-leaflet#135]
I am transforming coordinates from latlng to pixel and back with 

`this.map.unproject([this.width, 0], this.maxZoom);`

and

`this.map.project(layer.getLatLng(),this.maxZoom);`

The second function throws an exception "TypeError: Cannot read property 'project' of undefined".

I am working with L.CRS.Simple

**Comment by reblace** [comment]
For whatever reason, where you're using the ```project``` method, ```this.map``` is undefined. You need to make sure you aren't trying to use the ```this.map``` variable until you've assigned it.

If you're setting ```this.map``` inside of the (leafletMapReady) callback, make sure you aren't referencing it until after it's set.

**Comment by razfazz** [comment]
Thank you for the help and you are right!

I am experiencing something really strange.

With the following code 

```
 this.map.on(L.Draw.Event.CREATED, function (e) {

                console.log('map: ' + this.map);

              });
```
The output is "map: undefined". I am wondering how this can happen.
I try to figure it out and get back when I solved it. 

EDIT:

```
 let mapref = this.map;
this.map.on(L.Draw.Event.CREATED, function (e) {

                console.log('map: ' + mapref );

              });
```

I do not understand why, but it is working when i store a local reference. Thank you very much for pointing me in the right direction

**Comment by reblace** [comment]
The issue you're likely encountering (you might have already figured this out) is that your ```this``` context is probably not correct. If you want to reference ```this.map``` you will need to bind ```this``` when you create your callback function.

See: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/bind
