### ISSUE TITLE
Marker css animations not working

### ISSUE THREAD

**Issue by Fraktalite** [bluehalo/ngx-leaflet#142]
Hi,
The project on which I'm working is a migration from an angularjs.
What I had and I cannot have now is the css animation on marker.
I specify the marker icon size in css instead of the IconOptions object, this is still working well. But animations using keyframes are not working anymore
Here is the code defining the icon:
```
let iconOptions : IconOptions = {
      className: 'highlighted',
      iconUrl: 'assets/images/markers/default.svg'
};
```

And here is the scss for the animation that scale up and down the icon:
```
@keyframes scale {
    0%   {width:16px; height:16px; margin-left:-8px; margin-top:-8px;}
    50%  {width:24px; height:24px; margin-left:-12px; margin-top:-12px;}
    100% {width:16px; height:16px; margin-left:-8px; margin-top:-8px;}
}
```
```
.leaflet-marker-icon{
    margin-left:-8px;
    margin-top:-8px;
    width:16px;
    height:16px;    
    transition: all 0.2s ease; 
    will-change: transform;

    &.highlighted{
        animation: scale 1s ease;
        animation-iteration-count: infinite;
    }
}
```

Of course the scss is in a global one and I've checked that it's collectly applied on the marker in the chrome dev tools.

So it's in chrome but has no effects and this is working in the angularjs version.

Any ideas?

Many thanks in advance.

Sébastien

**Comment by reblace** [comment]
I've never tried messing with animated effects on things like Markers. Do you have a live example I could look at or a repo with some code I could check out?

**Comment by Fraktalite** [comment]
Hi reblace,

I created a simple exemple from scratch to show you but it's working. So I think that my issue is maybe not related to ngx-leaflet directly, maybe more due to the complexity of my application. I will continue to investigate to find what is the root cause of this behavior.

It's very strange; what can disable completely css animations on the layers?

I'll keep you on track.

Thank you

**Comment by reblace** [comment]
I'm going to close this for now. If you find a specific issue with ngx-leaflet, feel free to open another issue. If you have general questions for how to get your specific use case working, try asking on StackOverflow. Thanks!

**Comment by dpadula** [comment]
I'm in the same situation here. [This example](https://codepen.io/jmfolds/pen/MJzoPO) works perfectly. In addition: [this](https://stackoverflow.com/questions/41884070/how-to-make-markers-in-leaflet-blinking) idea is clear but in angular, nothing happens. 
To clarify more the situation, when you create the marker:

     return L.circleMarker([latLon.lat, latLon.lng], {
        color: sensible ? '#660000' : '#003e3e',
        fillOpacity: sensible ? 0.85 : 0.6,
        fillColor: sensible ? '#FF0000' : '#4ca3a3',
        className: sensible ? 'pulse' : '',
        weight: 2,
        radius: 3 + this.map.getZoom() / 4
      });
You can add a CSS class to animate (in this case) the opacity of marker

.pulse {
    animation: pulsate 1s ease-out infinite alternate;
    opacity: 1.0;
}
@keyframes pulsate {
    0% { opacity: 0.0;}
    50% { opacity: 1.0;}
    100% { opacity: 0.0;}
}

 but nothing happens.

What's the interesting here? when you add the CSS class to marker in element inspector in Chrome, then voilá! the animation works.

Maybe adding the CSS class when the map finish some particular event?

Thanks

**Comment by andreagosto** [comment]
try to put the style/animation in the main styles.scss, i don't know why, but for me animations and styles for map's elements, work only if they are in the main css file, and don't work in component.css.

**Comment by reblace** [comment]
Read about Angular style scoping vs global styles. Component styles are scoped by default to prevent styles from having side effects on other components. But, that means that when you want to style a nested component like the Leaflet map, you usually need to make those styles in the global style files. That's why @andreagosto is seeing that behavior (I believe).

@dpadula is the problem that the class is missing from the marker? Or that the animation isn't working despite the class existing on the marker?
