### ISSUE TITLE
Gis using NGX leaflet

### ISSUE THREAD

**Issue by Zahma** [bluehalo/ngx-leaflet#145]
I have developed a leaflet based library using js that plays with polygons, merges them, and permits selection.
I want to integrate this library to angular, so I want to adapt my code to angular.
Can I construct advanced GIS manipulations (merge, draw ... etc) using  GX leaflet & NGX Leaflet Draw?
Can I construct a tooltip with NGx leaflet ?

**Comment by reblace** [comment]
You can use https://github.com/Asymmetrik/ngx-leaflet-draw and https://github.com/Asymmetrik/ngx-leaflet-markercluster as examples of how to create an Angular extension that extends ngx-leaflet.

There's also the https://www.asymmetrik.com/ngx-leaflet-and-leaflet-plugins/ guide with a GitHub repo full of examples of how to integrate external libraries with Angular and ngx-leaflet.

**Comment by reblace** [comment]
I'm gonna close this since I provided links to relevant guides. Thanks!
