### ISSUE TITLE
Preserve the order of rendering base layers group and overlays group in layers control.

### ISSUE THREAD

**Issue by ciukstar** [bluehalo/ngx-leaflet#148]
Preserve the order of displaying base layers group and overlays group in layers control as defined in the component: 

this.layersControl = { overlays: { ... }, baseLayers: { ... } }

vs this.layersControl = { baseLayers: { ... }, overlays: { ... } }. 

Or provide other way to specify the order.

**Comment by reblace** [comment]
Please edit your issue. You have the description in the title.

**Comment by reblace** [comment]
Are you asking for the ability to affect how these two things are arranged in the on-map layers control?

Does changing the order of the properties have any impact on this in regular Leaflet?

**Comment by ciukstar** [comment]
Too insignificant.
