### ISSUE TITLE
Leaflet functions not being imported?

### ISSUE THREAD

**Issue by wvarneriii** [bluehalo/ngx-leaflet#151]
I have followed the README to every end except for the module importing into the component module because my application does not have component modules and uses only the app module.  I am still importing LeafletModule. Functions like latLng and tileLayer are not being recognized by the compiler and as a result, I cannot get a map to run.

**Comment by reblace** [comment]
Did you try following this tutorial: https://github.com/Asymmetrik/ngx-leaflet-tutorial-ngcli

You have to import either those functions individually or the Leaflet module into `L`. And, you also have to import the typings for Leaflet.

**Comment by wvarneriii** [comment]
I imported directly into the component and it worked. Thanks!
