### ISSUE TITLE
Question: what about plugins?

### ISSUE THREAD

**Issue by atodd-geoplan** [bluehalo/ngx-leaflet#155]
I am not sure the leaflet plugins work here.

`import { latLng, tileLayer } from 'leaflet';`

ensures leaflet-src.js is loaded, that will be the second time overwriting any amends made by the plugin.
the first time is in scripts.bundle,js

see: https://github.com/angular/devkit/issues/565

for more detail

also describe here: https://github.com/angular/angular-cli/wiki/stories-global-scripts

**Comment by reblace** [comment]
See this repo (https://github.com/Asymmetrik/ngx-leaflet-tutorial-plugins) and this tutorial (https://www.asymmetrik.com/ngx-leaflet-and-leaflet-plugins/) for a detailed exploration of how plugins work with ngx-leaflet and angular CLI.

They both talk about how to deal with module scoping and local vs global dependencies.

**Comment by atodd-geoplan** [comment]
@reblace not sure how i missed that given the amount of googling I have been doing the last two days.

does this mean that if I have 7 plugins, that's the same 7 imports I need to do in all the files I reference leaflet via?

`import { latLng, tileLayer } from 'leaflet';`

**Comment by reblace** [comment]
Yeah, you'd need to import it everywhere you're referencing it. The tutorial repo includes several  examples with slightly different scenarios. Some dependencies need to be global so they are available as transitive dependencies.

Most of the Leaflet plugins needs to be stacked on top of Leaflet, e.g.,

```
import * as L from 'leaflet';
import 'ngx-leaflet-draw';
```

**Comment by phihochzwei** [comment]
Honestly: You should post those links in the README. I faced the same problem and the solution is yet so easy. Thx
