### ISSUE TITLE
Integrating leaflet.shapefile

### ISSUE THREAD

**Issue by Fitssum** [bluehalo/ngx-leaflet#156]
Hi,

I followed the guidance to integrate the leaflet.shapefile (https://www.asymmetrik.com/ngx-leaflet-and-leaflet-plugins/). I'm trying to integrate the plugin in Angular 4 app built with ngx-leaflet. I took the following actions:
- since it doesn't have npm package, I downloaded the leaflet.shapefile from GitHub repo and added it in my node_modules repo
- I imported the package in my component using:
import * as L from 'leaflet';
import './node_modules/leaflet-shapefile/shp.js';

However, when I run ng build, it is giving me "Module not found: Error: can't resolve..."

Am I missing the steps? Grateful for your kind guidance.

Thanks a lot!

**Comment by reblace** [comment]
Ensure that

```
import './node_modules/leaflet-shapefile/shp.js';
```

is a relative path to the node_modules directory. It's likely you have to go up at least a couple directories to get there.

**Comment by Fitssum** [comment]
Thanks a lot @reblace.
I edited the relative path to be: import '../../../node_modules/leaflet-shapefile/shp.js';
I can be able to build the application now.
Thanks again

**Comment by reblace** [comment]
Np, I'll close this then. Thanks!
