### ISSUE TITLE
Map not scrollable with Chrome 65

### ISSUE THREAD

**Issue by LaurentArtusio** [bluehalo/ngx-leaflet#157]
Using:
Angular 5.2.9
ngx-leaflet 3.0.2-10-g96d4460
leaflet 1.3
When I run the demo with "gulp dev" as described at https://github.com/Asymmetrik/ngx-leaflet/blob/master/README.md#install

It works with both firefox and ie, but in Chrome 65 the map appears "frozen", not scrollable. Changing zoom is possible however.

Thanks

**Comment by reblace** [comment]
Do you have this issue with Chrome 65 with vanilla Leaflet (i.e., Just Leaflet, no Angular)?

**Comment by reblace** [comment]
I'm running Chrome Version 65.0.3325.181 (Official Build) (64-bit) On Mac OSX and can't reproduce the issue. What OS are you on?

**Comment by alexgoldstone** [comment]
Doesn't help resolve the issue but thought it would be useful to get third-party confirmation... I can confirm the following is working for me and my map can be dragged:

```
Chrome Version 65.0.3325.181 (Official Build) (64-bit) on Mac OS X.
"leaflet": "^1.3.1"
"@asymmetrik/ngx-leaflet": "^3.0.2"
```

**Comment by LaurentArtusio** [comment]
Ok it works now. It seems that was a temporary problem with my Chrome browser, and after a reinstallation it's working.

Really sorry for the inconvenience and the unnecessary investigation.

**Comment by Shib-TPF** [comment]
I'm having this same problem with both development mode on Chrome (Version 68) and Android (Tested on Android 8 and 9). Dragging is working fine on iOS though.

I'm using Ionic and have the map inside a component on one of my pages. Every other feature works beautifully across all devices (including Chrome when it's not in dev mode). It's just dragging isn't working in dev mode on Chrome and when I build the app onto Android devices. Attempting to drag the map either doesn't move the map at all, or it moves it about 20px in the drag direction.

The leafletMapMove events are definitely being fired and the event is being sent though - it's just not showing the drag properly.

Chrome Version: Version 68.0.3440.106 (Official Build) (64-bit)
"@asymmetrik/ngx-leaflet": "^4.0.0"
"leaflet": "^1.3.3"
