### ISSUE TITLE
google map style

### ISSUE THREAD

**Issue by serbasii** [bluehalo/ngx-leaflet#160]
google map style does not implemented! how can it?

**Comment by reblace** [comment]
I'm not sure what you're asking. Are you trying to use Google Map tile layers? Leaflet supports this, you just need to use the right tile server URLs. You should Google "Using Google Map tile layers with Leaflet."

**Comment by serbasii** [comment]
Yeah, this is great and working. But i want to style the google tile layer like this [http://jsfiddle.net/fJFWN/232/](url)

ref: [https://developers.google.com/maps/documentation/javascript/reference/3/#MapOptions](url)

**Comment by reblace** [comment]
Is L.Google in the core Leaflet package or is it a separate library? If it's the latter, you'd want to follow some of the examples here: https://github.com/Asymmetrik/ngx-leaflet-tutorial-plugins to see how to integrate it. Then, you should be able to create the same Google Leaflet layers directly like you do in the Fiddle.
