### ISSUE TITLE
How to keep track of the drawn layers

### ISSUE THREAD

**Issue by Zahma** [bluehalo/ngx-leaflet#161]
[leafletLayers] takes an array of polygons. How can I keep track of the polygons present in the array. for instance assume I have 3 markers each representing a store. How can I know, in the array, which element belongs to which store ?

**Comment by wvarneriii** [comment]
You could loop through the elements in the array and just console.log() them.

**Comment by reblace** [comment]
There are a lot of ways depending on what you're trying to accomplish.

You can use .apply and .bind to inject the data object into event callbacks when you register them if you're trying to make it easy to find the right object on layer events.

You can keep the objects in your own data structure that maps between objects and layer objects (e.g., polygons, markers, etc.).

It mostly depends on which direction you're trying to map. If it's object -> layer, then it's pretty easy to just have a map of object id -> { object, layer }. If it's layer -> object, you might have to do equality checks on an array of {object, layer}, or you use the bind/apply approach I mentioned.

There isn't really a "Leaflet" way to do this. These suggestions are more general programming approaches.

**Comment by reblace** [comment]
I'm gonna close this cause I think I addressed the question. Thanks!
