### ISSUE TITLE
White lines shown in rendering.

### ISSUE THREAD

**Issue by wvarneriii** [bluehalo/ngx-leaflet#162]
Using Leaflet 1.3.1
ngx-leaflet 2.5
Angular 4.4.5

I am rendering the map in a modal and in some cases, white lines will form on the map like so: 
![image](https://user-images.githubusercontent.com/32345834/40195357-49ea602e-59db-11e8-9bb7-6f0c4b247166.png)

Here is another example when resizing the window: 
![image](https://user-images.githubusercontent.com/32345834/40195539-c02bbbb6-59db-11e8-8d67-21e01e4b116a.png)

For the modal styling itself my code is: 
`modal-dialog {
        height: 100vw;
        margin: 30px auto;
        width: 126vw;
        .devices-sm({
            height: 70vh;
            width: 88vh;
        });
        .modal-content {
            height: 100%;
            .modal-body {
                background-color: @accent-background-color;
                height: 100%;
                padding: 0;
                #map {
                    height: 100%;
                    position: relative;
                    width: 100%;
                    z-index: 0;
                }
            }
        }
    }`

The map is simply set to fitbounds([[82, -160], [-79, 180]]);

**Comment by reblace** [comment]
I'm not entirely sure what you're seeing here. Do you only see it with this baselayer? Or does it happen with any baselayer you use? I wonder if it's a fractional pixel alignment issue or something with the baselayer.

**Comment by wvarneriii** [comment]
This happens with any baselayer. It does look like it could be a fractional pixel alignment issue. Especially with the way it behaves. Any info you need that I could give? Coworkers have tried on their machines and they have a similar issue.

**Comment by sblaauw** [comment]
There is an issue about this in Leaflet. See the discussion here: https://github.com/Leaflet/Leaflet/issues/6101

**Comment by reblace** [comment]
I'm going to close this as it's a documented issue in Leaflet. See that thread for status and details.
