### ISSUE TITLE
leafletOptions is not reseting on click of map

### ISSUE THREAD

**Issue by dev-amitkmishra** [bluehalo/ngx-leaflet#167]
I have 2 leaflet map. On clicking map1, map2 should reflect the changes. The values of leafletOptions are changing but not reflecting in the map. Please help in re-rendering of an already created map with angular6.

**Comment by reblace** [comment]
The leafletOptions are set when the map is created. They are not intended to be mutable. Changes to them won't be reflected. Consult the docs for the specific things that can be modified (e.g., layers, layer controls, zoom, center, etc.). Other settings that aren't exposed as input bindings can be set directly on the map object which you can get using the (leafletOnMapReady) output binding.
