### ISSUE TITLE
How to apply filters on a layer

### ISSUE THREAD

**Issue by dev-amitkmishra** [bluehalo/ngx-leaflet#168]
Hi,

I am looking for applying filters on a layer. 'SetParams' method is present in leaflet library, but I am not able to find setparams method, where I can apply CQL_FILTER. Please help in a way, with which I can apply filters on the preloaded map, because reloading whole map with all layers is not a feasible option.

**Comment by reblace** [comment]
Anything not exposed through ngx-leaflet can be done directly on the map instance, see the README docs regarding how to get a handle to the map using (leafletOnMapReady). Additionally, these kinds of help questions should be asked on StackOverflow. Please limit issues on this repo to bugs or feature requests. Thanks!
