### ISSUE TITLE
ERROR in node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(7,30): error TS2709: Cannot use namespace 'LatLng' as a type.

### ISSUE THREAD

**Issue by Sanantita** [bluehalo/ngx-leaflet#172]
Hi,

I'm using your libraries and typedefs in my Angular 6 project, but I get the following error:

ERROR in node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(7,30): error TS2709: Cannot use namespace 'LatLng' as a type.

My package.json file:

{
  "name": "apex",
  "version": "4.1.0",
  "license": "",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "6.0.3",
    "@angular/common": "6.0.3",
    "@angular/compiler": "6.0.3",
    "@angular/core": "6.0.3",
    "@angular/forms": "6.0.3",
    "@angular/http": "6.0.3",
    "@angular/platform-browser": "6.0.3",
    "@angular/platform-browser-dynamic": "6.0.3",
    "@angular/platform-server": "6.0.3",
    "@angular/router": "6.0.3",
    "@asymmetrik/ngx-leaflet": "^4.0.0",
    "@asymmetrik/ngx-leaflet-markercluster": "^1.0.0",
    "@ng-bootstrap/ng-bootstrap": "^1.0.2",
    "@types/jquery": "^3.3.1",
    "@types/leaflet": "^1.2.7",
    "@types/leaflet.markercluster": "^1.0.3",
    "bootstrap": "4.0.0",
    "bourbon": "^5.0.0",
    "chart.js": "^2.7.2",
    "chartist": "^0.11.0",
    "classlist.js": "^1.1.20150312",
    "core-js": "^2.5.3",
    "intl": "^1.2.5",
    "jquery": "^3.3.1",
    "leaflet": "^1.3.1",
    "leaflet.markercluster": "^1.3.0",
    "ng-chartist": "^2.0.0-beta.1",
    "ng2-charts": "^1.6.0",
    "ngx-quill": "^3.1.0",
    "node-sass": "^4.7.2",
    "resize-observer-polyfill": "^1.4.2",
    "rxjs": "^6.2.0",
    "rxjs-compat": "^6.2.0",
    "screenfull": "^3.3.1",
    "web-animations-js": "^2.2.5",
    "zone.js": "^0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.6.6",
    "@angular/cli": "6.0.7",
    "@angular/compiler-cli": "6.0.3",
    "@angular/language-service": "6.0.3",
    "@types/chartist": "^0.9.41",
    "@types/jasmine": "^2.8.6",
    "@types/node": "^9.4.7",
    "codelyzer": "^4.2.1",
    "jasmine-core": "^3.1.0",
    "jasmine-spec-reporter": "^4.2.1",
    "karma": "^2.0.0",
    "karma-chrome-launcher": "^2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.4.2",
    "karma-jasmine": "^1.1.1",
    "karma-jasmine-html-reporter": "^1.0.0",
    "protractor": "^5.3.0",
    "ts-node": "^5.0.1",
    "tslint": "^5.7.0",
    "typescript": "2.7.2"
  }
}

What do I miss?

Thanks,
Ariel

**Comment by reblace** [comment]
Are you using ng cli from scratch?
Did you follow or fork the tutorial here? https://asymmetrik.com/ngx-leaflet-tutorial-angular-cli/

**Comment by Sanantita** [comment]
Well, I do a cli project from scratch and it works well, Buy when I try to put it on my original Angular 6 projects I get: 

ERROR in node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(7,30): error TS2709: Cannot use namespace 'LatLng' as a type.

I do the same steps in my project that I do in the new one.

What can I do to get my project compiled?

Thanks!

**Comment by reblace** [comment]
Is your Angular 6 project an angular cli project? Can you provide more context from your project code or share your repo?

**Comment by reblace** [comment]
So, it's hard to tell exactly what's going on. But it's complaining that it thinks LatLng is a namespace. It's supposed to be a type. So, I don't know if somehow you have some type definitions somewhere that are either declaring LatLng as a namespace or importing LatLng incorrectly.

It might be useful for you to try adding some of the Leaflet related stuff from your project into a fresh working ng cli project piece by piece until you find the specific thing that creates the issue. Then, you can troubleshoot from there.

**Comment by MiVvlt** [comment]
I have the same issue

**Comment by reblace** [comment]
The fastest way for me to diagnose this is for someone to provide a GitHub repo with an example that reproduces the issue.

**Comment by gem85247** [comment]
same issue here

**Comment by MiVvlt** [comment]
I can't really share my code, but I think the error is in @types/leaflet, I get the following error output:

ERROR in node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(7,30): error TS2709: Cannot use namespace 'LatLng' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(10,10): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(15,14): error TS2709: Cannot use namespace 'MapOptions' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(16,28): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(19,13): error TS2709: Cannot use namespace 'LatLng' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(20,32): error TS2709: Cannot use namespace 'LatLng' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(21,16): error TS2709: Cannot use namespace 'LatLngBounds' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(22,16): error TS2709: Cannot use namespace 'LatLngBounds' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(25,27): error TS2709: Cannot use namespace 'LeafletMouseEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(26,33): error TS2709: Cannot use namespace 'LeafletMouseEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(27,31): error TS2709: Cannot use namespace 'LeafletMouseEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(28,29): error TS2709: Cannot use namespace 'LeafletMouseEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(29,31): error TS2709: Cannot use namespace 'LeafletMouseEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(30,31): error TS2709: Cannot use namespace 'LeafletMouseEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(31,29): error TS2709: Cannot use namespace 'LeafletEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(32,34): error TS2709: Cannot use namespace 'LeafletEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(33,32): error TS2709: Cannot use namespace 'LeafletEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(34,29): error TS2709: Cannot use namespace 'LeafletEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(35,34): error TS2709: Cannot use namespace 'LeafletEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(36,32): error TS2709: Cannot use namespace 'LeafletEvent' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.d.ts(42,15): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leaflet.directive.wrapper.d.ts(7,15): error TS2314: Generic type 'Map<K, V>' requires 2 type argument(s).
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/layers/leaflet-tile-layer-definition.model.d.ts(14,67): error TS2709: Cannot use namespace 'TileLayer' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/layers/leaflet-tile-layer-definition.model.d.ts(25,24): error TS2709: Cannot use namespace 'TileLayer' as a type.
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/layers/leaflet-tile-layer-definition.model.d.ts(32,24): error TS2709: Cannot use namespace 'TileLayer' as a type.

**Comment by reblace** [comment]
Can you look in your lock file for npm or yarn to see what version of ngx-leaflet, leaflet, and @types/leaflet you're using?

**Comment by reblace** [comment]
Closing this due to lack of response. The best I can guess is that this is a mismatch of typescript/angular/leaflet/typings versions.
