### ISSUE TITLE
Map displaced in leaflet-container

### ISSUE THREAD

**Issue by people-ware** [bluehalo/ngx-leaflet#176]
On the initial view the map is displaced like this
![image](https://user-images.githubusercontent.com/10436633/43251917-9177845e-90c1-11e8-87c8-81d7921abec2.png)

After manually resizing the screen the view is correctly updated:
![image](https://user-images.githubusercontent.com/10436633/43251959-b461bffc-90c1-11e8-9153-c4aff36bce01.png)

That's why I use this workaround:
```
ngAfterViewInit(): void {
    window.dispatchEvent(new Event('resize'));
}
```

Maybe you can reproduce this behavior and fix the initialization.
I'm using

- Angular CLI 1.7.4
- Angular 5.2.7
- Chrome 67

My template:
```
<div style="height: 250px;"
    leaflet
    [leafletOptions]="options">
</div>
```

My component:
```
optionsSpec: any = {
    layers: [{ url: 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', attribution: 'Open Street Map' }],
    zoom: 10,
    center: [ 52.52, 13.41 ]
};

// Leaflet bindings
options = {
    layers: [ tileLayer(this.optionsSpec.layers[0].url, { attribution: this.optionsSpec.layers[0].attribution }) ],
    zoom: this.optionsSpec.zoom,
    center: latLng(this.optionsSpec.center)
};
```

**Comment by people-ware** [comment]
I also tried
```
onMapReady(map: Map) {
    map.invalidateSize();
}
```
with no success.

**Comment by reblace** [comment]
Are you using any kind of layout system (e.g., Bootstrap, jquery UI, etc.)? Or, are you dynamically showing/hiding the map or any of its parent divs?

If any of those are the case, you have to call invalidate size after the page layout is complete. A simple test is to wrap your map.invalidateSize() call in a setTimeout() with a delay of something like 100ms. If that makes it work, then you need to figure out how to add invalidateSize calls in response to the completion of the page layout. (Or add something that will periodically check the size of the map div, and once it has stabilized, call invalidateSize())

**Comment by people-ware** [comment]
Thank you for the answer! That was causing it.
`invalidateSize` can be hooked in the component's `AfterViewInit`:

```
ngAfterViewInit() {
    this.map.invalidateSize();
}
```

**Comment by reblace** [comment]
It sounds like you're good. I'm gonna close this issue, if you have any other issues, open a new issue. Thanks!
