### ISSUE TITLE
Circle Market do not triguer event click

### ISSUE THREAD

**Issue by cdchn1989** [bluehalo/ngx-leaflet#177]
Hi guys i have a interesting issue, when I have a maker this can trigger a event but when is not a marker for example, circleMarker, pilygon (any layer) this not works fine, really i have no idea what happen.

In this code work when is a marker

```
   L.marker([ response['data'][i]['lat'], response['data'][i]['lon']], {
      icon: L.icon({
         iconSize: [ 25, 41 ],
         iconAnchor: [ 13, 41 ],
         iconUrl: 'assets/marker-icon.png',
         shadowUrl: 'assets/marker-shadow.png'
      }),
      riseOnHover:true
   }).on('click', (ev) => {
     this.openEndPointDialog(response['data'][i]);
   });
```

In this code not work when isn't a marker

```
   L.circleMarker([ lat, lng],
      {
         radius: 15,
         color: this.colorRoute[aux['indexView']],
         fillOpacity: 0.6,
         weight: 1
      }
   ).on('click', (ev) => {
      this.openEndPointDialog(response['data'][i]);
   });

**Comment by sblaauw** [comment]
I'm able to get circle marker working using ngx-leaflet using very similar code.

`
L.circleMarker([51.5, -0.09], {
      radius: 15,
      color: '#0f0',
      fillOpacity: 0.6,
      weight: 1
    })
      .on('click', e => {
        console.log(e);
      })
      .addTo(leafletMap);
`
Note that I'm getting "leafletMap" from the (leafletMapReady) event referenced here:
https://github.com/Asymmetrik/ngx-leaflet/#leafletmapready-map

**Comment by reblace** [comment]
It's likely the issue you're encountering is related to change detection. When you do something inside of an event handler that is being emitted from within Leaflet, you need to make sure that any operations you perform that Angular needs to know about are performed inside the Angular zone.

In the example below, I wrap the code running inside the handlers in an NgZone `run` call. Without doing this, the message doesn't update when I click on the markers.
```
<div style="height: 300px; width: 300px;"
  leaflet
  [leafletOptions]="options"
  [leafletLayers]="layers"></div>

{{message}}
```

```
import { Component, NgZone } from '@angular/core';
import { circleMarker, icon, latLng, marker, tileLayer } from 'leaflet';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  options = {
    layers: [
      tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '...' })
    ],
    zoom: 5,
    center: latLng(46.879966, -121.726909)
  };

  message: string;

  layers = [
    marker(latLng(46.879966, -121.726909), {
      icon: icon({
        iconSize: [ 25, 41 ],
        iconAnchor: [ 13, 41 ],
        iconUrl: 'assets/marker-icon.png',
        shadowUrl: 'assets/marker-shadow.png'
      }),
      riseOnHover:true
    }).on('click', () => {
      this.zone.run(() => {
        this.message = 'marker click';
      });
    }),
    circleMarker(latLng(46.4, -121.5), {
      radius: 15,
      color: '#ff0000',
      fillOpacity: 0.6,
      weight: 1
    }).on('click', (ev) => {
      this.zone.run(() => {
        this.message = 'circle marker click';
      });
    })
  ];

  constructor(private zone: NgZone) {}

}

```
