### ISSUE TITLE
leafletLayersControl not updated when dynamically adding a new layer in overlays

### ISSUE THREAD

**Issue by jamestlc** [bluehalo/ngx-leaflet#181]
Scenario:
in my layersControl:

layersControl = {
        overlays: {
            City: L.tileLayer.wms(....),
            Airport: L.tileLayer.wms(.....)
        }
};

when I work in my compoent.ts, when I click on the map, I will base on the lat lon to place a marker on the map and dynamically add a new layer by geojson data, and I want the geojson layer added into the overlay, so I do the following:

const style = {
            color: '#666',
            weight: 5.0,
            opacity: 0.5,
            fill: false
};
const cafe = new L.geoJSON(cafe_data, {style: function() { return style; } } );
const cafe_name = cafe_data[0];
this.layersControl.overlays[cafe_name] = cafe;
this.layersControl.overlays[cafe_name].addTo(this.map);

Outcome:
I can see the layer on the map, but the layerscontrol is not updated.
But if I uncheck and check other existing overlays (e.g. City), the newly added overlay will be appear on the layerscontrol.
Is it due to the applyOverlayChanges function in LeafletControlLayersWrapper class not activated?

Thank you.

Regards,
James

**Comment by reblace** [comment]
Can you provide more of the context of the code above (and format it properly)?
Also, which version on ngx-leaflet are you using?

It's likely that something is causing change detection to not work. You shouldn't have to manually call ".addTo(this.map)" as the plugin handles that for you. Depending on the event you're responding to when you add the new overlay, you may need to run the change in the Angular zone or invoke change detection manually.

Thanks!

**Comment by jamestlc** [comment]
@reblace Thank you for your reply. I am using version 3.0.2
Enclosed are the component ts file and the html file for your reference. Thank you!


[Temp.zip](https://github.com/Asymmetrik/ngx-leaflet/files/2288828/Temp.zip)

**Comment by jamestlc** [comment]
The issue fixed when I upgraded the library to version 4.0.0, thank you.
