### ISSUE TITLE
Tooltip not showing in the correct position

### ISSUE THREAD

**Issue by kylekrzeski** [bluehalo/ngx-leaflet#183]
My issue is that the tooltip is showing in the wrong position when using bindTooltip (it shows up in the correct position using bindPopup):
![tooltip-off](https://user-images.githubusercontent.com/1596741/45038532-6341ac80-b02f-11e8-99a8-63d8be6ea348.PNG)

My layer looks like this:
```
geoJSON(
  (state),
  {
    onEachFeature: function (feature, l) {
      l.bindTooltip("N/A", {
        permanent: true,
        opacity: 0.7,
        direction: 'top'
      });
    }
}

```
I've seen a couple of things [somewhat similar](https://github.com/miguelcobain/ember-leaflet/issues/165) floating around, but I'm pretty sure this one is an ngx-leaflet issue. I'm seeing this behavior when permanent is true or false.

Thanks in advance for taking a look at this.

**Comment by zellb** [comment]
Im having this issue too, it happens only the first time when loading markers with tooltip. Changing zoom level makes tooltip move to correct location

**Comment by reblace** [comment]
I noticed that I had to set the `tooltipAnchor` option in the marker icon to get the tooltip to line up correctly. This is because we have to use a custom marker to get the markers to show up in Angular.io.

See the following code:

```
import { Component } from '@angular/core';
import { icon, latLng, marker, tileLayer } from 'leaflet';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  options = {
    layers: [
      tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '...' })
    ],
    zoom: 5,
    center: latLng(46.879966, -121.726909)
  };

  layers = [
    marker(latLng(46.879966, -121.726909), {
      icon: icon({
        iconSize: [ 25, 41 ],
        iconAnchor: [ 13, 41 ],
        iconUrl: 'assets/marker-icon.png',
        shadowUrl: 'assets/marker-shadow.png',
        tooltipAnchor: [ 0, -41 ]
      }),
      riseOnHover:true
    }).bindTooltip("N/A", {
      permanent: true,
      opacity: 1,
      direction: 'top'
    })
  ];

}
```

If there's something unique to using geoJSON or binding the tooltip after the layer is added to the map, I don't think there's anything that the Angular plugin is doing that would cause the problem.

**Comment by Sampath-Lokuge** [comment]
@reblace Thanks. This works nicely for me.
