### ISSUE TITLE
 ng build/serve --prod strange map zoom effect

### ISSUE THREAD

**Issue by holyzhopa** [bluehalo/ngx-leaflet#187]
Hello I'm using ngx-leaflet im my angular application. And i faced a problem using ng build prod. There are strange zoom and tile replacing effect.
 Steps to reproduce:
1) Follow the instructions on https://asymmetrik.com/ngx-leaflet-tutorial-angular-cli/ section GETTING AND RUNNING THIS TUTORIAL.
2) Run example with `ng server --prod`
3) Zoom in and out slowly

Expected behavior (ng serve)
[normal_behavior.zip](https://github.com/Asymmetrik/ngx-leaflet/files/2471648/normal_behavior.zip)

Current behavior(ng serve --prod). Looks like it blurs and then all tiles
 load together [prod_behavior.zip](https://github.com/Asymmetrik/ngx-leaflet/files/2471650/prod_behavior.zip)

I attached video but quality isn't so good. So better to reproduce on pc.

**Comment by petitlen** [comment]
me too!!!,what happen?
ng serve is ok,but ng serve --prod is very slow when zoom

**Comment by holyzhopa** [comment]
@petitlen Not sure if the problem still persists, because I can't reproduce It. Actually I did nothing to fix it except updating my npm dependencies. So maybe It will help you

**Comment by holyzhopa** [comment]
@petitlen I faced this issue again and investigated the problem a bit. Seems like this issue is related with build optimization(because i faced issue when enabled this option). Here is the discussion about that https://github.com/angular/angular-cli/issues/11439. Hope this information will help you.
