### ISSUE TITLE
LeafletModule is not an NgModule

### ISSUE THREAD

**Issue by mariuspruski** [bluehalo/ngx-leaflet#19]
app.module.ts
`import {LeafletModule} from "@asymmetrik/angular2-leaflet";`
`@NgModule({`
`  providers: [],`
`  imports: [NgxChartsModule, BrowserModule, FormsModule, LeafletModule],`
`  declarations: [AppComponent, LeafletMapComponent],`
`  bootstrap: [AppComponent]`
`})`
`export class AppModule { }`

**ERROR in LeafletModule is not an NgModule**

**Comment by reblace** [comment]
Can you include your package.json? Also, are you using the angular-cli? And are you on TS 2.1?
Could it be related to this: https://github.com/angular/angular/pull/13294 
or this: https://github.com/angular/angular-cli/issues/3426 ?

Another question would be are you using AOT? or JIT compiler?

I can't reproduce this on master and I've updated everything to the latest dependencies on the develop branch and everything still seems to work fine.

**Comment by twmiller** [comment]
I'm seeing the same thing on an Angular-cli project.  @angular/cli 1.0.0-beta.31, TS 2.1.4, angular 2.4.7.  Interestingly, it's only on the first build.  As soon as you save a file and the project re-compiles, the error goes away. :/

**Comment by reblace** [comment]
That issue I link above says that the angular CLI isn't guaranteed to work with TS 2.1+

I think there's a merged PR on angular CLI that's supposed to fix this but it hasn't been pushed yet. I think the solution is if you're using angular CLI, make sure you are using less than TS 2.1

**Comment by twmiller** [comment]
Thanks, I'm not super concerned about it at the moment, as this app is a ways out from production, just thought I'd chime in.  I'll give the TS version change a shot.

**Comment by reblace** [comment]
Gonna close this for now since I think this is related to an Angular-CLI/Typescript 2.1 compatibility issue. If someone can reproduce this outside of the context of Angular-CLI using Typescript 2.1 feel free to comment here and I can reopen the issue.
