### ISSUE TITLE
Angular Reactive forms doesn't update on ngx-leaflet popup custom element

### ISSUE THREAD

**Issue by throwawaygit000** [bluehalo/ngx-leaflet#190]
I have a component that implements angular reactive forms and I created a custom element to add it to ngx-leaflet poup but properties like markerForm.valid , markerForm.status and markerForm.value are not updated.

When I use the same component outside leaflet popup it works properly.

```
<form [formGroup]="markerForm" (ngSubmit)="onSubmit(markerForm)" novalidate>
      <div class="form-group">
   <label class="center-block">description:
    <input class="form-control" id="description" 
 formControlName="description"  
    ></label>
     </div>
  <button type="submit" class="btn btn-success">Save</button>
</form>
{{ markerForm.valid | json }}
Form value: {{ markerForm.value | json }}
Form status: {{ markerForm.status | json }}
```

component form creation 
```
this.markerForm = this.fb.group({
       description: ['', Validators.required ]
    });
```

**Comment by jalu14** [comment]
Happens to me aswell, fixed it by using a ChangeDetectorRef and detectChanges(), don't know about another workaround.

**Comment by reblace** [comment]
Yeah, those click events are going to happen outside of the angular zone, so you're going to have to use ChangeDetectorRef and detectChanges() as described in the README: https://github.com/Asymmetrik/ngx-leaflet#a-note-about-change-detection

**Comment by reblace** [comment]
Going to close this as I think we've provided the solution: `detectChanges()`
