### ISSUE TITLE
[Feature request] Add 'zoom to bounds' to layerscontrol

### ISSUE THREAD

**Issue by pmeems** [bluehalo/ngx-leaflet#191]
Also asked on https://stackoverflow.com/questions/52852154/add-zoom-to-bounds-to-ngx-leaflet-layerscontrol

I need a way to zoom to the bounds of selected/specific layers. I think the best solution would be to add a button to the LayersControl since this control already has the layers and is the most logical please to do layer-wide changes.

I hope you understand what I mean ;)

**Comment by reblace** [comment]
That does sound like a nice feature for Leaflet itself or an idea for a custom Leaflet plug-in.

ngx-leaflet only tries to expose existing functionality of Leaflet. So, we wouldn't implement that feature in this component. You could submit this as a feature request directly on the Leaflet Github repository or create a Leaflet plugin that implements this functionality.
