### ISSUE TITLE
layer control empty overlay checkbox's checked true

### ISSUE THREAD

**Issue by serbasii** [bluehalo/ngx-leaflet#193]
Hi,
i'm adding empty overlay into layer control;

```
layersControl = {
      baseLayers: {
        '.': this.options.layers[0],
      }, overlays: {
        A: L.tileLayer(''),
        B: L.tileLayer('')
      }
    };
```

while running appears checkbox as false, how can i set as default true the checkbox?

**Comment by reblace** [comment]
For layers that are controlled by a layers control, if you want them to be added to the map by default, you need to add them to the layers array at initialization. In other words,

```
layerA: L.tileLayer('');
layerB: L.tileLayer('');

options = {
    layers: [ L.tileLayer(''), this.LayerA, this.layerB ]
};

layersControl = {
    baseLayers: {
        '.': this.options.layers[0],
    }, overlays: {
        A: this.layerA,
        B: this.layerB
    }
};
```

The layers control is synced with the map, so adding the overlays to the map at initialization will make them checked in the layers control.

**Comment by serbasii** [comment]
Yes. Worked when added to options. Thanks.
