### ISSUE TITLE
Rerendering labels on zoom

### ISSUE THREAD

**Issue by Varshamathukumalli** [bluehalo/ngx-leaflet#207]
Hi,

I am displaying labels on polygons using divIcon.
On zoom, i want to modify the width of the icon dynamically.
Is there any event, so that we can listen to and modify the width/height of the icons.

**Comment by reblace** [comment]
Check this section of the README: https://github.com/Asymmetrik/ngx-leaflet#map-events

It covers all of the map events on which you can register a callback. I'm not sure how you'd go about changing the size of the divIcon in response (that's more of a pure Leaflet question), but the event you'd likely want to register for is `leafletMapZoomEnd `.

**Comment by Varshamathukumalli** [comment]
@reblace , I got the event. But is there any way to update the height/width of the divIcon on such events

**Comment by reblace** [comment]
You'd have to do it manually. In that event, you'd need to iterate over all the div icons and change the sizes (if Leaflet allows that). This is something I'm not positive that Leaflet itself allows.
