### ISSUE TITLE
WMS tilelayer bounds not respected in query

### ISSUE THREAD

**Issue by Rahkeesh** [bluehalo/ngx-leaflet#211]
I cannot post the exact code I'm using here but I have done up a demo that can be put together fairly easily that should demonstrate the error almost as well. The version of angular/leaflet/ect. come directly from there.

To put the demo together.
-- start with the demo given here: https://asymmetrik.com/ngx-leaflet-tutorial-angular-cli/
-- to get leaflet.coordinates working follow the instructions given here: https://github.com/Asymmetrik/ngx-leaflet-tutorial-plugins/tree/master/Leaflet.Coordinates
-- Replace the contents of your app.component.ts with the code below.

```
import { Component } from '@angular/core';
import { latLng, Map, tileLayer, TileLayer } from 'leaflet';

declare const L: any; // Leaflet
import '../../node_modules/leaflet.coordinates/dist/Leaflet.Coordinates-0.1.5.src.js';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

// Define our base layers so we can reference them multiple times
streetMaps = new TileLayer.WMS('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
  crs: L.CRS.EPSG4326,
});

tracts = new TileLayer.WMS('https://demo.boundlessgeo.com/geoserver/wms', {
  layers: 'opengeo:tracts',
  crs: L.CRS.EPSG4326,
  transparent: true,
  format: 'image/png',
  bounds: L.latLngBounds([[44, -93], [44.25, -92.75]])
});

layersControl = {
  baseLayers: {
    'Street Maps': this.streetMaps,
  },
  overlays: {
    'Countries': this.tracts
  }
};

  options = {
    layers: [ this.streetMaps, this.tracts ],
    zoom: 7,
    center: latLng([ 45, -95 ])
  };

  onMapReady(map: Map) {
    L.control.coordinates().addTo(map);
  }
}
```

For the purpose of familiarizing yourself with the demo layer we're looking at, you may wish to comment out the bounds the first time you boot it up.

You should be able to quickly observe that the section of the map that the query dishes up is considerably larger than the bounds given. It's even more obvious in my application. It appears to segment the map into large slices and then use the bounds to determine which large sections to query but does not get any more specific than that. The size of these larger sections is determined by how zoomed out the map is, therefore as you zoom in or out, you'll notice that more/less of the layer is displayed (generally speaking, the closer you'll zoom in the better it'll match the given bounds but that's no guarantee).

In my application, I'd be using several massive layers with numerous features in each but will occasionally need to do some precise filtering so that only a single feature (or a feature and all features within a very small geographic radius) are displayed at a time. I'd assumed that I'd be able to use the bounds on the layer to accomplish this but this issue is proving a challenge to that, particularly as the area displayed changes with the zoom level. I have been able to create queries that return appropriate images by mimicking the query that ngx-leaflet sends and then modifying the bbox so I'd assume that if I could take control of how ngx-leaflet queries for images/puts images on the map that I'd be able to hack together a solution but AFAIK ngx-leaflet is not built to allow that and if it is, I'm not sure how I'd do it.

**Comment by reblace** [comment]
ngx-leaflet doesn't control the querying of the tile layers, it's just a wrapper that manages the integration between Leaflet and Angular.io. The issue you're having is likely coming from the Leaflet library: https://leafletjs.com/

**Comment by Rahkeesh** [comment]
Alright, I'll bring up my issue there then.

**Comment by reblace** [comment]
closing this as it will be brought up as a Leaflet issue.
