### ISSUE TITLE
Map overflows container, has erratic display

### ISSUE THREAD

**Issue by LucasFrecia** [bluehalo/ngx-leaflet#224]
I have used leaflet before in an angular 7 app and never witnessed an issue like this one. The map overflows its container and takes huge portion of scrren, and doesnt display correctly even when tampering with css or diferent setups. I can't say this is a leaflet bug, but since I've had it working in other proyecs and can't make it work with pretty much same config, maybe someone knows what is going on here. 

![wird-map-2](https://user-images.githubusercontent.com/5466293/58387991-ac3af600-7fee-11e9-9ec3-4e58aa8f39ca.gif)

I have a simple leaflet container:
```html
<div  style="height: 300px;"
         leaflet
         [leafletOptions]="options"
         [(leafletZoom)]="options.zoom"
         [(leafletCenter)]="options.center"
         (leafletMapReady)="onMapReady($event)">
</div>
```

And basic leaflet Typescript:
```ts
  public options = {
    layers: [
      tileLayer(
        'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
        { maxZoom: 18, attribution: '...' }
      )
    ],
    zoom: 15,
    center: latLng(46.879966, -121.726909)
  };

  onMapReady(map: Map): void {
    setTimeout(() => {
      // Link: https://github.com/Leaflet/Leaflet/issues/690#issuecomment-5741031
      map.invalidateSize();
    });
  }
```

Here is my package json:

```json
{
  "name": "frontend",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "7.2.15",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "7.2.15",
    "@angular/compiler": "7.2.15",
    "@angular/core": "7.2.15",
    "@angular/flex-layout": "7.0.0-beta.24",
    "@angular/forms": "7.2.15",
    "@angular/material": "7.3.7",
    "@angular/platform-browser": "7.2.15",
    "@angular/platform-browser-dynamic": "7.2.15",
    "@angular/router": "7.2.15",
    "@angular/service-worker": "^7.2.15",
    "@asymmetrik/ngx-leaflet": "^5.0.2",
    "@ngxs/devtools-plugin": "^3.4.3",
    "@ngxs/logger-plugin": "^3.4.3",
    "@ngxs/router-plugin": "^3.4.3",
    "@ngxs/schematics": "^0.0.1-alpha.5",
    "@ngxs/storage-plugin": "^3.4.3",
    "@ngxs/store": "^3.4.3",
    "core-js": "^2.5.4",
    "hammerjs": "^2.0.8",
    "leaflet": "^1.5.1",
    "ngxs-reset-plugin": "^1.1.0",
    "rxjs": "~6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.29"
  },
  "devDependencies": {
    "@types/leaflet": "^1.4.4",
    "@angular-devkit/build-angular": "~0.11.0",
    "@angular/cli": "^7.3.9",
    "@angular/compiler-cli": "~7.1.0",
    "@angular/language-service": "~7.1.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~3.1.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.1.6"
  }
}


```

**Comment by reblace** [comment]
This behavior is most commonly either that the Leaflet CSS file is missing or that something is changing the size of the map container and you aren't calling `map.invalidateSize()`.

If you resize the browser window and it magically fixes the issue, it's the `map.invalidateSize()` issue. If that doesn't change the behavior, it's most likely missing CSS.

**Comment by LucasFrecia** [comment]
I was missing the css my bad

**Comment by AhmedEzz71090** [comment]
I have the same problem, I used map.invalidateSize(). and ensured I have the CSS file and problem still persist

**Comment by Alessio18911** [comment]
Hello! The same for me: I've made a nice lazy-load leaflet map in JS, but just after enqueueing it in Wordpress, the issue appeared. I couldn't fix it and had to add leaflet Wordpress plugin. I added the map shortcode in a post and custom markers I output with JS. But even in this case the issue sometimes appear after the page is reloaded, but not that horror I had had in the morning.
