### ISSUE TITLE
onMouseOut event missing

### ISSUE THREAD

**Issue by essentin** [bluehalo/ngx-leaflet#225]
Like in the title. I'm using newest ngx-leaflet release (5.0.1 i belive) and `onmouseout` event seems to be missing in `leaflet.directive`.

**Comment by reblace** [comment]
Huh... yeah, that event is totally missing. If you're feeling ambitious, you could put in a PR off the develop branch. You can mimic how the other events are handled. Otherwise, I'll take care of it when I get a chance. Though, I'm pretty slammed this month.

Thanks for noticing!

**Comment by reblace** [comment]
PR is in for Angular v8 that includes this change.

**Comment by reblace** [comment]
ngx-leaflet v6.x provides this event now. It's also the release that supports Angular v8. If you need it back-ported to Angular 7, let me know.
