### ISSUE TITLE
BUG: Angular 8.2 errors with "Can't resolve all parameters for LeafletDirective"

### ISSUE THREAD

**Issue by justixnl** [bluehalo/ngx-leaflet#233]
When installing / importing the ngx-leaflet into an Angular 8.2 project it throws a "Can't resolve all parameters for LeafletDirective" error (pictured below).

In a project with Angular 7.0.1 the exact same code works fine.
See details below. Thanks.

# versions

Angular: 8.2
Leaflet:
    "@asymmetrik/ngx-leaflet": "^5.0.1",
    "@asymmetrik/ngx-leaflet-markercluster": "^2.0.0",
    "@types/leaflet-markercluster": "^1.0.3",
    "@types/leaflet.markercluster": "^1.0.3",
    "leaflet": "^1.3.4",
    "leaflet.markercluster": "^1.4.1",

# error:
![error](https://i.imgur.com/FCSLSQ2.png)

# code that fails
```js
import { LeafletModule } from "@asymmetrik/ngx-leaflet";
import { LeafletMarkerClusterModule } from "@asymmetrik/ngx-leaflet-markercluster";

...
 imports: [
...
    LeafletModule.forRoot(),
    LeafletMarkerClusterModule
  ],
```

**Comment by reblace** [comment]
For Angular 8, you need ngx-leaflet 6 and ngx-leaflet-markercluster 3:

```
    "@asymmetrik/ngx-leaflet": "^6.0.1",
    "@asymmetrik/ngx-leaflet-markercluster": "^3.0.0",
    "@types/leaflet": "^1.5.1",
    "@types/leaflet.markercluster": "^1.4.0",
    "leaflet": "^1.5.1",
    "leaflet.markercluster": "^1.4.1",
```

See if that resolves the issue.

**Comment by justixnl** [comment]
> For Angular 8, you need ngx-leaflet 6 and ngx-leaflet-markercluster 3:
> 
> ```
>     "@asymmetrik/ngx-leaflet": "^6.0.1",
>     "@asymmetrik/ngx-leaflet-markercluster": "^3.0.0",
>     "@types/leaflet": "^1.5.1",
>     "@types/leaflet.markercluster": "^1.4.0",
>     "leaflet": "^1.5.1",
>     "leaflet.markercluster": "^1.4.1",
> ```
> 
> See if that resolves the issue.

I am afraid updating the leaflet packages didn't solve anything as I am still getting the same error. I am gonna recheck all my Angular packages and make sure they are all up-to-date. will let you know if this solves anything

**Comment by reblace** [comment]
If you can share a Git repo with the issue I can troubleshoot. I suspect it's a dependency issue. I created a clean working example with angular CLI with the versions I referenced above and I couldn't reproduce the compile error.

**Comment by justixnl** [comment]
After troubleshooting all day yesterday I found out it has to do with the core-js dependency. To be specific version 3.2.1. I reverted back to last version of 2 and it works now. I also have problems using ngx-moment so it probably has something to do with the core-js (version 3) dependency itself. So I think this ticket can be closed.
