### ISSUE TITLE
style attribute used with leafletBaseLayers

### ISSUE THREAD

**Issue by pcnate** [bluehalo/ngx-leaflet#239]
- [x] Review the README
- [x] Tell us what version of Leaflet, Angular, and ngx-leaflet you're using
- [x] Include code that reproduces your issue

leaflet: 1.5.1
angular: 8.2.8
ngx-leaflet: 4.0.0 & 6.0.1

Using leaflet as the docs describe by setting a style height on the div breaks.
```
  <div leaflet style="height:540px"
    [leafletOptions]="options"
    [leafletBaseLayers]="baseLayers"
    [leafletLayersControlOptions]="controlOptions"
    (leafletMapZoomEnd)="zoomEnd( $event )"
    (leafletMapReady)="onMapReady( $event )"
  >
```

![image](https://user-images.githubusercontent.com/621940/65785406-e988cf00-e119-11e9-9161-727cc8771e54.png)

This works just fine:

```
  <div leaflet 
    [leafletOptions]="options"
    [leafletBaseLayers]="baseLayers"
    [leafletLayersControlOptions]="controlOptions"
    (leafletMapZoomEnd)="zoomEnd( $event )"
    (leafletMapReady)="onMapReady( $event )"
  >
```

Used with

```
.leaflet-container {
  height: 540px;
}
```

**Comment by reblace** [comment]
I know this is a bit late of a response, but usually that error implies that there is something wrong that caused the plugin to fail to load or that there's something wrong with the 'leaflet' directive not getting applied to the element.

Are you sure there isn't a typo in your HTML that's causing it to not recognize the 'leaflet' attribute? Or, that you aren't forgetting to import the LeafletModule into your module and app module?

All of the demo examples in the ngx-leaflet project use the style attribute to size the map. You can check out the project and use 'npm install && npm run demo' to see the demo.

**Comment by reblace** [comment]
Closing cause no response
