### ISSUE TITLE
Request: Add the relevant  package versions to angular versions to the README

### ISSUE THREAD

**Issue by SSmale** [bluehalo/ngx-leaflet#240]
Please could you add/ let me know the relevant versions to angular versions and i would be happy to make a PR (for hacktober) with the changes to the README to let other devs know.

Current list
```
ngx-leaflet 3.x latest is ng5
ngx-leaflet 2.x latest is ng4
```

**Comment by reblace** [comment]
It's all documented in the CHANGES.md file. We could mod the README to point people in that direction.

**Comment by SSmale** [comment]
Ahh didn’t even think to look there!
