### ISSUE TITLE
Methods of Overlays and Layers  are not recognised in ng8

### ISSUE THREAD

**Issue by jamesbcn** [bluehalo/ngx-leaflet#242]
Neither circle, polygon nor marker are being recognised in Angular 8.

**Comment by jamesbcn** [comment]
Closed this too soon. Overlays are not appearing

**Comment by reblace** [comment]
Can you be more specific? Is this a compilation or runtime issue? Is it types related or is it something failing to render on the map?

**Comment by jamesbcn** [comment]
Run-time.

Apologies but I didn't have the time to wait (I'm now using another map). Importing removed any error but still nothing appeared.

**Comment by reblace** [comment]
If you can provide a reference to a repo with a project that reproduces the issue, I can take a look. Otherwise, I can't reproduce it.
