### ISSUE TITLE
Error while compiling code for leaflet

### ISSUE THREAD

**Issue by danishshaikh42** [bluehalo/ngx-leaflet#243]
Hello,

I am using the below versions 
Angular  - 8 version
Typescript - 3.6.3

and my package.json file looks like this:

"dependencies": {
    "@angular/animations": "~8.1.1",
    "@angular/common": "~8.1.1",
    "@angular/compiler": "~8.1.1",
    "@angular/core": "~8.1.1",
    "@angular/forms": "~8.1.1",
    "@angular/platform-browser": "~8.1.1",
    "@angular/platform-browser-dynamic": "~8.1.1",
    "@angular/router": "~8.1.1",
    "@asymmetrik/ngx-leaflet": "^5.0.2",
    "@asymmetrik/ngx-leaflet-draw": "^5.0.1",
    "leaflet": "^1.5.1",
    "leaflet-draw": "^1.0.4",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },

  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.1",
    "@angular/cli": "~8.1.1",
    "@angular/compiler-cli": "~8.1.1",
    "@angular/language-service": "~8.1.1",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/leaflet": "^1.5.2",
    "@types/node": "~8.9.4",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3"
  }

I am getting the below error:
ERROR in node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts:8:28 - error TS2694: Namespace '"F:/leafletGeofence/node_modules/@types/leaflet/index".Control' has no exported member 'Draw'.

8     drawControl: L.Control.Draw;
                             ~~~~
node_modules/@asymmetrik/ngx-leaflet-draw/dist/leaflet-draw/core/leaflet-draw.directive.d.ts:10:28 - error TS2694: Namespace '"F:/leafletGeofence/node_modules/@types/leaflet/index".Control' has no exported member 'DrawConstructorOptions'.


Kindly suggest what's wrong here.

**Comment by Alexsius-t** [comment]
In your dependecies there's no sign of @types/leaflet-draw.

**Comment by reblace** [comment]
As @Alexsius-t stated, you need to 'npm install @types/leaflet-draw'.

Closing as this recommendation should address the compilation issue.
