### ISSUE TITLE
Error when calling click on a marker

### ISSUE THREAD

**Issue by jegjessing** [bluehalo/ngx-leaflet#244]
I made the mistake of running npm update on my project, rendering it impossible to build :-( due to 
 error TS2345: Argument of type '"click"' is not assignable to parameter of type '"tileunload" | "tileloadstart" | "tileload"'.

My package.json has the following:
"@types/leaflet": "^1.5.3",
"@types/leaflet-draw": "^1.0.1",
and
"@asymmetrik/ngx-leaflet": "^6.0.1",
"@asymmetrik/ngx-leaflet-draw": "^5.0.1",
Why it says tileunload etc I do not know the code is as follows:

let correctionMarker: Marker;
      correctionMarker = marker([correction.pos_x, correction.pos_y], {
        icon: icon({
          iconSize: [25, 41],
          iconAnchor: [13, 41],
          iconUrl: 'leaflet/marker-icon.png',
          shadowUrl: 'leaflet/marker-shadow.png'
        })
      });
      (correctionMarker.options as any).id = correction.id;
      correctionMarker.on('click', (clickEvent: MouseEvent) => {
        this.currentMarker = (clickEvent as any).sourceTarget;
        this.currentPos = this.currentMarker.getLatLng();
        this.zone.run(() => {
          self.editCorrection(correction);
        });
      });
      correctionMarker.addTo(this.markerLayer);
    });

**Comment by reblace** [comment]
Can you remove your node-modules directory and do a full 'npm install'?

If the issue persists, can you share an example project that reproduces the issue?

**Comment by jegjessing** [comment]
I've done that, but I just found out, that if I remove the event type then it works fine.
So to make it work I changed it from:
`correctionMarker.on('click', (clickEvent: MouseEvent) => {`
to
`correctionMarker.on('click', (clickEvent) => {`
And now it runs beautifully, only problem is that the editor no longer recognizes the arguments to event, but I can live with that

**Comment by reblace** [comment]
I suspect this was an issue with Leaflet typings, which are known to change in ways that break things from time to time.
