### ISSUE TITLE
RangeError: Maximum call stack size exceed

### ISSUE THREAD

**Issue by jzrbsv** [bluehalo/ngx-leaflet#247]
Hi, everyone.

I asked this question on stackoverflow firstly [link](https://stackoverflow.com/questions/59053421/panto-new-latlng-onmapmove-maximum-call-stack-size-exceeded) but got no answers.

I'm trying to recenter my map when users move too far from the inital lat / lng and I'm doing it listening the (leafletMapMove) event.

But then this error occurs:
![Screenshot from 2019-11-26 11-42-15](https://user-images.githubusercontent.com/17956938/69812689-6fcf9900-11cf-11ea-8e44-1b5b2c01fbd0.png)

Here's the code I'm trying to accomplish this goal:
```
onMapMove($event) {
    const center = this.map.getCenter();
    if(center.lng < this.__INITIAL_LONG - this.offsetX_LEFT || center.lng > this.__INITIAL_LONG + this.offsetX_RIGHT ||
center.lat < this.__INITIAL_LAT - this.offsetX_LEFT || center.lat > this.__INITIAL_LAT + this.offsetX_RIGHT){

  this.map.panTo(new LatLng(this.__INITIAL_LAT+5, this.__INITIAL_LONG));
  setTimeout( () => {
    this.map.setZoom(this.__INITIAL_ZOOM);  
  }, 400);
}
```
In the setup I've added the option to prevent MoveStartEvent when use panTo method.

`panOptions: PanOptions = {
    noMoveStart: true
}`

**Comment by reblace** [comment]
It's on SO, I believe this is a bug in the poster's code, so we'll handle it on SO unless we discover a specific issue or bug with the library.
