### ISSUE TITLE
Support of angular 9/10

### ISSUE THREAD

**Issue by Araknailuben** [bluehalo/ngx-leaflet#256]
Hi,

I was wondering if support of angular 9 and angular 10 was planed.

I updated my project from angular 8 to 9 and all went good. No obvious error in leaflet component but my map has a strange behavior. Like it does not fill my page, markers are not displayed. I made no change in the code related to leaflet during the upgrade of angular so I am suspicious about an incompatibility and wanted to ask about here... 

Maybe it is just that I was doing something in the wrong way before and that was working by miracle but I really don't known. 

Is there someone who had issues with angular 9 and leaflet ?

Thanks for your time.
Wendy

**Comment by paulolira73** [comment]
have the same problem!... [leafletLayers]="Layers" load when create map, but not update when you destroy arrat layers or push new markers...

visibility of map i solved with this funtion on ts:

onMapReady(map: Map) {

    this.map = map;

    // refresh Map

    setTimeout(() => {
      console.log('1');
      this.map.invalidateSize();
    }, 1);
  }

and calling this funtion in html:

(leafletMapReady)="onMapReady($event)"

Please solution for update layers problem!!

**Comment by reblace** [comment]
Yeah, I'm planning to release an update soon. Likely this week.

**Comment by Araknailuben** [comment]
Thank you so much ! I look forward to get it !

**Comment by vaydich** [comment]
Hi!

What about ng9 support?

**Comment by reblace** [comment]
Yeah, working it now. It's a little more complicated than I expected.

**Comment by reblace** [comment]
v7 is published to npm. Let me know if you have any issues.

**Comment by kt215** [comment]
@paulolira73 Thanks for the visibility fix!!!

@reblace I still saw the visibility issue mentioned above after upgrading to ng 9.1.0 and ngx-leaflet 7.0.0. I'm also using ngx-leaflet-markercluster 3.0.0. @paulolira73's visibility fix resolved the issue for me (only the top 20% of the map was visible). Interestingly, the issue was not reproducible in development env, only when using deployed artifacts (ng build ...); not sure if that matters.

**Comment by reblace** [comment]
Do you want to create a separate ticket for the visibility issue and I can
look into it?
