### ISSUE TITLE
Shows wrong map of India

### ISSUE THREAD

**Issue by ckchinmay** [bluehalo/ngx-leaflet#258]
**Map for India is wrong.**
Map shown by your library (Wrong) -
![image](https://user-images.githubusercontent.com/63281716/78638098-4f27f600-78c9-11ea-81bb-1e4c821adba1.png)

Map shown by google (Right) -
![image](https://user-images.githubusercontent.com/63281716/78638232-8eeedd80-78c9-11ea-91b4-55d3c3e2f480.png)

**Please correct this.**

**Comment by paulmichaelstafford** [comment]
Lad, this could open up a whole new can of worms:

https://www.cnet.com/news/google-maps-changes-political-borders-based-on-whos-viewing-report-says/

**Comment by reblace** [comment]
You are referencing an Open Street Map map provided by https://www.openstreetmap.org

They are not affiliated with Leaflet and ngx-leaflet. If you have a concern with one of their maps, you should open an issue with them.

**Comment by akhileshsharma** [comment]
Leaflet does not show Correct maps for Bharat (India). This API should be avoided by any Indian developer, company, app until its fixed by providers.

**Comment by DarkMortal** [comment]
> Leaflet does not show Correct maps for Bharat (India). This API should be avoided by any Indian developer, company, app until its fixed by providers.

They have also shown Aksai Chin as part of China

**Comment by reblace** [comment]
See above comment thread.

The maps being rendered are provided by Open Street Map. They aren't being provided by Leaflet. You can configure Leaflet and ngx-leaflet to show maps and layers from whatever provider you choose.

**Comment by DarkMortal** [comment]
> See above comment thread.
> 
> The maps being rendered are provided by Open Street Map. They aren't being provided by Leaflet. You can configure Leaflet and ngx-leaflet to show maps and layers from whatever provider you choose.

That reply wasn't meant for you to begin with. "They" has been referred to Open Street Map
