### ISSUE TITLE
Source maps warning when compiling with Angular 9

### ISSUE THREAD

**Issue by looorent** [bluehalo/ngx-leaflet#263]
Using Angular CLI, every call to `ng serve` and `ng build` produces this warning:
```
WARNING in ./node_modules/@asymmetrik/ngx-leaflet/__ivy_ngcc__/dist/leaflet/layers/control/leaflet-control-layers-changes.model.js
Module Warning (from ./node_modules/source-map-loader/index.js):
(Emitted value instead of an instance of Error) Cannot find SourceMap 'leaflet-control-layers-changes.model.js.map': Error: Can't resolve './leaflet-control-layers-changes.model.js.map' in '/usr/src/app/node_modules/@asymmetrik/ngx-leaflet/__ivy_ngcc__/dist/leaflet/layers/control'
```
List of files in warning:
* `leaflet-control-layers-changes.model.js.map`
* `leaflet-control-layers-config.model.js.map`
* `leaflet-control-layers.wrapper.js.map`
* `leaflet-tile-layer-definition.model.js.map`
* `leaflet.directive.wrapper.js.map`
* `leaflet.util.js.map`

Versions:
* This issue occurs with both ngx-leaflet `6.x.x` and `7.0.0`.
* Tested on Angular `9.0.0` and `9.1.2`
* Ivy is enabled

ng-leaflet is only imported in a single Typescript file like this:
```
import { LeafletModule } from "@asymmetrik/ngx-leaflet";
```

**Comment by reblace** [comment]
Is this easy to reproduce with a standalone project? Can you make a Git repo that I can check out and test?

**Comment by looorent** [comment]
This occurs when enabling `projects.<project-title>.architect.build.sourceMap.vendor` in `angular.json`.

You can execute `ng serve` on these sources to reproduce it: https://github.com/looorent/asymmetrik_ngx-leaflet-issue-263

Looking at the bundle, several files actually refer to source maps that are missing. For instance, `cat node_modules/@asymmetrik/ngx-leaflet/__ivy_ngcc__/dist/leaflet/core/leaflet.directive.wrapper.js` produces:
```
[...]
//# sourceMappingURL=leaflet.directive.wrapper.js.map%
```
and `leaflet.directive.wrapper.js.map` does not exist.

**Comment by reblace** [comment]
Can you do a fresh npm install and then look in ./node_modules/@asymmetrik/ngx-leaflet/dist/leaflet and see if the sourcemaps are there? Cause, I do see them in the bundle I'm publishing to npm.

I cloned your repo and did an npm install and ng serve and didn't see any errors and the source maps are contained in the npm package.

**Comment by looorent** [comment]
The sourcemaps are there but not properly moved to `__ivy_ngcc__/dist/leaflet`. Apparently, this occurs randomly (but most of the time). So i guess this is a problem with ivy ngcc.

**Comment by reblace** [comment]
Oh, I see what you're saying now. Yeah, ivy generated the __ivy_ngcc__ directory correctly for me the couple times I've tried it.

**Comment by reblace** [comment]
I'm gonna close this and assume it's not an issue specifically with ngx-leaflet. If you find anything that suggests it is something specific to this library, comment and we can dig into it more.

**Comment by henriquearthur** [comment]
@looorent did you find a way to make the warning disappear?

**Comment by looorent** [comment]
@henriquearthur No, I still get the same (random) warning using these versions:
* `"@asymmetrik/ngx-leaflet": "8.1.0"`
* Angular 11.0.5

**Comment by henriquearthur** [comment]
I opened an issue in Angular as the problem appears to be with ngcc.

In the meantime I managed to remove the warnings by compiling ngx-leaftlet myself with `"enableIvy": true` on `tsconfig-lib.json`. Doesn't seem to cause any errors with the package itself but my use is very simple.

@reblace is it possible to enable Ivy by default on ngx-leaflet? Will cause any problems?
