### ISSUE TITLE
Missing tiles and tiles in the wrong place

### ISSUE THREAD

**Issue by imbakassinn** [bluehalo/ngx-leaflet#265]
I'm using leaflet 1.6.0, ngx-leaflet 7.0.0, Angular CLI 9.1.1 on Ubuntu 18.04

When I put in demo code I get tiles in the wrong place with white spaces in between. This is my code:

```
import { Component, OnInit } from '@angular/core';
import { latLng, tileLayer } from 'leaflet';

@Component({
  selector: 'app-map',
  templateUrl: './map.component.html',
  styleUrls: ['./map.component.css']
})
export class MapComponent implements OnInit {
  options = {
    layers: [
      tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; OpenStreetMap contributors'
      })
    ],
    zoom: 7,
    center: latLng([ 64, -21.726909 ])
  };

  constructor() { }

  ngOnInit(): void {
  }

}
```
```
<div class="map"
     leaflet
     [leafletOptions]="options">
</div>
```
And this is what the outcome looks like:
![image](https://user-images.githubusercontent.com/4348724/81700070-b5b7ab00-9457-11ea-8aa9-0ab04c16513b.png)

Am I doing anything wrong or is this a bug?

**Comment by reblace** [comment]
Check out the README, I'd almost guarantee that this is that you aren't loading the leaflet CSS file properly.

**Comment by imbakassinn** [comment]
You were correct, the file I had had css extension but I tried to import lefalet.scss. It works correctly now. Thank you.
