### ISSUE TITLE
GeoJSON causing issues for leafletLayers

### ISSUE THREAD

**Issue by apauldev** [bluehalo/ngx-leaflet#266]
I have been building an app to outline states on a map using your plugin.
This is my component file.

```

import { CountryShapeService } from './../services/country-shape.service';
import { Component, OnInit } from '@angular/core';
import { latLng, tileLayer, polyline, circle, polygon, marker, geoJSON, map} from 'leaflet';

@Component({
  selector: 'app-leaflet-layer',
  templateUrl: './leaflet-layer.component.html',
  styleUrls: ['./leaflet-layer.component.scss']
})
export class LeafletLayerComponent implements OnInit {
  constructor(private countryShapeService: CountryShapeService) {}
  public iCoord;
  public layers = [
    circle([ 21.7679, 78.8718 ], { radius: 500000 })
  ];
  layersControl = true;
  options = {
    layers: [
      tileLayer('https://tiles.stadiamaps.com/tiles/alidade_smooth_dark/{z}/{x}/{y}{r}.png', { maxZoom: 5, attribution: '...' })
    ],
    zoom: 4,
    center: latLng(21.7679, 78.8718)
  };


  ngOnInit(): void {
    this.countryShapeService.getIndiaShape().subscribe(indiaCoordinates =>{
      this.iCoord = indiaCoordinates;
      this.layersControl = true;
    });
  }
}
```

This is my HTML file-
```
<div class="map-container">
  <div class="map-frame">
    <div id="map" leaflet [leafletOptions]="options" [leafletLayers]="iCoord">
    </div>
  </div>
</div>
```

I can get layers variable to work on the map. But my GeoJSON file doesn't work. The same file is working when using vanilla leaflet.
Note I had to rename the file to TXT to attach instead of geojson/json.
Please help, I am at my wits end. I have been able to get this to work using geoJSON(iCoord) + map.addLayer(iCoord). Is there some attachmethod for ngx-leaflet as well.

This is the error I am getting.

>  "Error trying to diff '[object Object]'. Only arrays and iterables are allowed"

[india_outline.txt](https://github.com/Asymmetrik/ngx-leaflet/files/4635862/india_outline.txt)

**Comment by reblace** [comment]
[leafletLayers] is supposed to take an array of layers. If you want to bind a single layer, either wrap it in an array or use [leafletLayer]

**Comment by apauldev** [comment]
Thanks a bunch. Seems like sticking the GeoJson in an Array and running the         geoJSON(indiaCoordinates) did the trick.
