### ISSUE TITLE
Angular 10 Compatibility

### ISSUE THREAD

**Issue by jziggas** [bluehalo/ngx-leaflet#275]
```
node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/leaflet.module.d.ts:3:23 - error TS2314: Generic type 'ModuleWithProviders<T>' requires 1 type argument(s).

3     static forRoot(): ModuleWithProviders;
```

https://angular.io/guide/migration-module-with-providers

**Comment by reblace** [comment]
Angular 10 update should be coming soon.

**Comment by stjimmy54** [comment]
Also @angular/cli throw error on `ng update @angular/cli @angular/core`
`Fetching dependency metadata from registry...
                  Package "@asymmetrik/ngx-leaflet" has an incompatible peer dependency to "tslib" (requires "1", would install "2.0.0").
× Migration failed: Incompatible peer dependencies found.
Peer dependency warnings when installing dependencies means that those dependencies might not work correctly together.
You can use the '--force' option to ignore incompatible peer dependencies and instead address these warnings later.`

**Comment by rraziel** [comment]
@reblace have you started working on the Angular 10 fix?
Not saying this to put pressure on you, it's just that if you haven't started maybe I can take a look.

**Comment by reblace** [comment]
Just released it. Let me know if you have any issues.

**Comment by reblace** [comment]
Oh, and thanks for the offer of help. I usually upgrade a template project "ngx-template" and then merge the updates into this one. So, if you ever wanted to help out, you could put in a PR on that project. Thanks!
