### ISSUE TITLE
map is hidden

### ISSUE THREAD

**Issue by MichalNemec** [bluehalo/ngx-leaflet#282]
in styles.scss imported @import "../node_modules/leaflet/dist/leaflet.css";
css is applied
no map is shown, if i disable position:absolute in .leaflet-pane .. its shown
tiles are wrong

latest leaflet and ngx-leaflet

Angular CLI: 10.0.5
Node: 12.18.2
OS: win32 x64

Angular: 10.0.8
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.5
@angular-devkit/build-angular     0.1000.5
@angular-devkit/build-optimizer   0.1000.5
@angular-devkit/build-webpack     0.1000.5
@angular-devkit/core              10.0.5
@angular-devkit/schematics        10.0.5
@angular/cdk                      10.1.3
@angular/cli                      10.0.5
@angular/material                 10.1.2
@ngtools/webpack                  10.0.5
@schematics/angular               10.0.5
@schematics/update                0.1000.5
rxjs                              6.5.5
typescript                        3.9.7
webpack                           4.43.0

![Untitled](https://user-images.githubusercontent.com/5663019/90831325-c2e01200-e343-11ea-8bb7-842c59888dfe.png)

**Comment by osw4l** [comment]
i think what you need add this to your main styles.css
`@import "~leaflet/dist/leaflet.css";`

**Comment by MichalNemec** [comment]
added at bottom of the file and i have no visible map, but html in there with tiles
https://stackblitz.com/edit/angular-ivy-muhbvk

for some reason its now showing properly when i modified this stackblitz:
https://stackblitz.com/edit/angular-ngx-leaflet-4ymjxd

**Comment by reblace** [comment]
Have you validated that the CSS file is actually getting loaded into your app? This is the textbook behavior when the CSS file isn't getting loaded.

**Comment by reblace** [comment]
Didn't hear back with more details. Closing. Most likely missing CSS.
