### ISSUE TITLE
TypeError: Cannot read property '_leaflet_pos' of undefined

### ISSUE THREAD

**Issue by rala72** [bluehalo/ngx-leaflet#302]
If this is a bug, issue, enhancement request, etc. verify the following before submitting your issue:

- [x] Review the README to see if your issue is covered, and pay particular attention to the [Getting Help](https://github.com/Asymmetrik/ngx-leaflet#help) section.
- [x] Tell us what version of Leaflet, Angular, and ngx-leaflet you're using
- [x] Include code that reproduces your issue

Angular: 10.2.5
Leaflet: 1.7.1
ngx-leaflet: 8.1.0

Stacktrace:
```ts
at getPosition (leaflet-src.js:2450)
    at NewClass._getMapPanePos (leaflet-src.js:4439)
    at NewClass._rawPanBy (leaflet-src.js:4235)
    at NewClass.invalidateSize (leaflet-src.js:3559)
    at leaflet.directive.js:162
    at ZoneDelegate.invoke (zone-evergreen.js:364)
    at Zone.run (zone-evergreen.js:123)
    at NgZone.runOutsideAngular (core.js:27485)
    at LeafletDirective.push.TTNa.LeafletDirective.doResize (leaflet.directive.js:160)
    at ZoneDelegate.invokeTask (zone-evergreen.js:399)
```

MWE: https://stackblitz.com/edit/angular-ngx-leaflet-leaflet-pos?file=src/app/app.component.ts

Explanation of what I'm doing (in my project; similar in MWE):
I have a map in a component which is only possible to see after a specific breakpoint (you have to interact to get it).
If you resize the window to get below it, it gets destroyed (BreakpointObserver using Bootstrap breakpoints).
That's the moment the exception is thrown.

I'm triggering invalidateSize withing that method of the component showing the map:
```ts
@HostListener('resize')
onMapReady(map: LeafletMap) {
    setTimeout(() => map.invalidateSize(), 1);
}
```

Maybe related:
[Leaflet#6981](https://github.com/Leaflet/Leaflet/issues/6981),
[Leaflet#5774](https://github.com/Leaflet/Leaflet/issues/5774)

**Comment by capc0** [comment]
same issue for me - however it looks more like a leaflet error.

the `invalidateSize` is also called from https://github.com/Asymmetrik/ngx-leaflet/blob/master/src/leaflet/core/leaflet.directive.ts#L240, which can cause this error

**Comment by rala72** [comment]
any updates or comments on this?
