### ISSUE TITLE
Angular 12 update issues

### ISSUE THREAD

**Issue by argupta23** [bluehalo/ngx-leaflet#303]
Updating an Angular 11 project to Angular 12 results in the following errors during compile.

Will appreciate any guidance on how to resolve it.

./node_modules/leaflet/dist/images/marker-icon-2x.png:1:0 - Error: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

./node_modules/leaflet/dist/images/marker-icon.png:1:0 - Error: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

./node_modules/leaflet/dist/images/marker-shadow.png:1:0 - Error: Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)

**Comment by CoffeeCreamer435** [comment]
Hey argupta23

I had the same problem as you at my job.
I was searching for a workaround and could not find that.
But I figured a way out. I only don't know how I did that exactly, but I have the repository for you.
Here is the repository: https://github.com/CoffeeCreamer435/leafletAngular12Example
My source is from: https://github.com/turingcs2005/leaflet

**Comment by argupta23** [comment]
@CoffeeCreamer435 
Thanks for the help. I will look into it shortly and provide an update on what I find.

**Comment by argupta23** [comment]
I was able to identify the issue. It was related to me having the following code within my component.ts

`L.Icon.Default.mergeOptions({
   iconRetinaUrl: require("leaflet/dist/images/marker-icon-2x.png"),
   iconUrl: require("leaflet/dist/images/marker-icon.png"),
   shadowUrl: require("leaflet/dist/images/marker-shadow.png"),
 });`

Angular 12 / Webpack 5 does not like it and spits the above error during compilation.

Hope this will help others running into the same issue.

@CoffeeCreamer435 Appreciate your help here. I have seen some React users report the same error as well.

**Comment by ElodieC** [comment]
I removed `import 'leaflet/dist/images/marker-icon.png';` from `src.main.ts` and then it compiles
