### ISSUE TITLE
Cannot read property '_layers' of undefined with map#addLayer during onMapReady event

### ISSUE THREAD

**Issue by 3l0w** [bluehalo/ngx-leaflet#305]
If this is a bug, issue, enhancement request, etc. verify the following before submitting your issue:

- [x] Review the README to see if your issue is covered, and pay particular attention to the [Getting Help](https://github.com/Asymmetrik/ngx-leaflet#help) section.
- [x] Tell us what version of Leaflet, Angular, and ngx-leaflet you're using
- [x] Include code that reproduces your issue

Leaflet: 1.7.1
ngx-ngxleaflet: 8.1.0
Angular: 12.2.0

I am tring to add marker after de loading of map (because i need to do a http request first)

map.component.html
```html
<div class="map"
     leaflet
     [leafletOptions]="options"
     (leafletMapReady)="onMapReady($event)">
</div>
```
map.component.html
```java
export class MapComponent {
  options: MapOptions = {
    layers: MapComponent.getLayers(),
    zoom: 6,
    center: new LatLng(48.858370, 2.294481)
  };

  constructor(private mapService: MapService) {
  }

  private static getLayers(): Layer[] {
    return [
      new TileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; OpenStreetMap contributors'
      }),
    ];
  }
  async onMapReady(map: Map) {
    const markers: Marker[] = await this.getMarkers();
    markers.forEach(map.addLayer)
  }

  private async getMarkers(): Promise<Marker[]> {
    const points = await this.mapService.getPoints();
    return points.map(value =>
      new Marker(
        new LatLng(value.latitude, value.longitude),
        {
          icon: new Icon({
            iconSize: [50, 41],
            iconAnchor: [13, 41],
            iconUrl: 'assets/red-marker.svg',
          }),
          title: "test"
        }
      )
    )
  }
}
```
With all this code my maps draw perfectly except for the markers i get this error:
```
ERROR TypeError: Cannot read property '_layers' of undefined
    at addLayer (leaflet-src.js:6620)
    at Array.forEach (<anonymous>)
    at map.component.ts:32
    at timer (zone.js:2561)
    at ZoneDelegate.invokeTask (zone.js:406)
    at Object.onInvokeTask (core.js:28659)
    at ZoneDelegate.invokeTask (zone.js:405)
    at Zone.runTask (zone.js:178)
    at invokeTask (zone.js:487)
    at ZoneTask.invoke (zone.js:476)
```

**Comment by reblace** [comment]
I was able to reproduce this. I played around a bit to figure out what was going on.

It seems to be specific to the fact that you're adding the layers to the map using:
```
markers.forEach(map.addLayer)
```

When I changed it to this way, it works:
```
markers.forEach((l) => l.addTo(map))
```

Alternatively, you could store the markers in an array and bind that array to the ```[leafletLayers]``` input binding and it would have the same affect.
