### ISSUE TITLE
Angular 13 Ivy Compatibility

### ISSUE THREAD

**Issue by olingerc** [bluehalo/ngx-leaflet#315]
Every time I build my angular 13 project I get this message
```
Processing legacy "View Engine" libraries:
- @asymmetrik/ngx-leaflet [module/esm5] (https://github.com/Asymmetrik/ngx-leaflet.git)
Encourage the library authors to publish an Ivy distribution.
```

I am using ngx-leaflet version 8.1.0.

I thought ngx-leaflet was already Ivy compatible?

**Comment by reblace** [comment]
Just published a new version for ng13. Let me know if you have any issues with it.
