### ISSUE TITLE
Support for Angular 14

### ISSUE THREAD

**Issue by SvenAtGit** [bluehalo/ngx-leaflet#335]
After upgrading my amgular project to version 14 i get an error on _**npm update**_

npm ERR! Found: @angular/common@14.0.1
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"^14.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"13" from @asymmetrik/ngx-leaflet@13.0.2
npm ERR! node_modules/@asymmetrik/ngx-leaflet
npm ERR!   @asymmetrik/ngx-leaflet@"^13.0.2" from the root project

**Comment by uap-universe** [comment]
A change of these lines would be required:

https://github.com/Asymmetrik/ngx-leaflet/blob/93d7958670ebbd5d8a70fc191a6aa1813aceff64/projects/ngx-leaflet/package.json#L14-L15

**Comment by Atgoogat** [comment]
I've submitted a PR https://github.com/Asymmetrik/ngx-leaflet/pull/336.

**Comment by hammamboumou** [comment]
I hope someone with write access notices this PR, this is really important for new projects. Maybe there should be more people with write access

**Comment by SvenAtGit** [comment]
Yes this is an important one! I am still waiting to upgrade my project to Angular 14 because of this issue, this is the only item that is blocking the upgrade for one of my projects.

**Comment by hammamboumou** [comment]
Maybe the solution is to fork the repo until they see this at @Asymmetrik

**Comment by uap-universe** [comment]
Maybe one of @andrewmarcus @brianghig @jrassa @luan-dev @rstjohn can prevent that yet another fork is born.

**Comment by luan-dev** [comment]
I will look at this soon

**Comment by reblace** [comment]
Working on it now...

**Comment by reblace** [comment]
Just published v14. Ping this thread if you have any issues w/it.

**Comment by reblace** [comment]
Closing, but will monitor in case anyone has issues w/v14
