### ISSUE TITLE
ngx-leaflet 16.0.0 published without building

### ISSUE THREAD

**Issue by mateusduraes** [bluehalo/ngx-leaflet#357]
Hello, it seems like the version 16.0.0 was published without building the code.
I've got errors when trying to import the module. After installing 15.0.1 it worked again.

Version 16.0.0 - code tab on npm
https://www.npmjs.com/package/@asymmetrik/ngx-leaflet/v/16.0.0?activeTab=code

Version 15.0.1 - code tab on npm
https://www.npmjs.com/package/@asymmetrik/ngx-leaflet/v/15.0.1?activeTab=code

**Comment by reblace** [comment]
Oh I know what I did. I’ll fix it tonight or tomorrow. Sorry about that.

**Comment by reblace** [comment]
Pushed 16.0.1. Let me know if it's still busted.
