### ISSUE TITLE
integrate angular2-leaflet with electron and map doesnt appear

### ISSUE THREAD

**Issue by FarhAnAbuBakar** [bluehalo/ngx-leaflet#36]
im trying to integrate angular2-leaflet with my application using electron and already copy exactly your code into my repository but map doesnt appear even it do not show any error...pls help me

**Comment by reblace** [comment]
Can you provide some example code? Or a pointer to your repo so I can see what you're doing?

**Comment by FarhAnAbuBakar** [comment]
my problem already fix by wrap all the component into my root module and the map working well.
