### ISSUE TITLE
Support Angular 18

### ISSUE THREAD

**Issue by pkurcx** [bluehalo/ngx-leaflet#367]
https://github.com/bluehalo/ngx-leaflet/pull/368

**Comment by muchbetterug** [comment]
+1

**Comment by Fiehra** [comment]
hi :) are you using SSR with this?

**Comment by Joshua35260** [comment]
+1

**Comment by reblace** [comment]
Just published 18.x. I published this version to both @asymmetrik and @bluehalo namespaces. I've been meaning to make that migration for a while.
