### ISSUE TITLE
Add the global css import step to setup documentation

### ISSUE THREAD

**Issue by chriszrc** [bluehalo/ngx-leaflet#40]
This looks really great so far, and the instructions are so nice and clean, but they exclude the fact that anyone starting with this project (especially using the angular cli), will also need to add that final step of including the global css in their `.angular-cli.json`

```
"styles": [
        "styles.css",
        "../node_modules/leaflet/dist/leaflet.css"
      ],
```

**Comment by reblace** [comment]
I added a section to the help docs that discusses how to get the styles set up correctly. Thanks for the feedback!
