### ISSUE TITLE
How to add GeoJSON layer to a map using [leafletLayers] in a directive?

### ISSUE THREAD

**Issue by hlherrera** [bluehalo/ngx-leaflet#45]
I'm trying to add a GeoJSON layer, but not work?

in component.html
...
 leaflet style="height: 400px;"
			     [leafletOptions]="options"
			     [leafletPanOptions]="panOptions"
			     [leafletZoomOptions]="zoomOptions"
			     [leafletZoomPanOptions]="zoomPanOptions"
			     [leafletFitBoundsOptions]="fitBoundsOptions"
			     [leafletZoom]="zoom"
			     [leafletCenter]="center"
			     [leafletBaseLayers]="baseLayers"
			     [leafletLayersControlOptions]="layersControlOptions"
				 [leafletLayers]="layers"
			     (leafletMapReady)="initMap($event)">

in component.ts
...
this.layers = [L.geoJSON(this.geodata)];

Thanks.

**Comment by reblace** [comment]
The README isn't super clear about this, but you aren't supposed to use '[leafletBaseLayers]' and '[leafletLayers]' at the same time. The '[leafletBaseLayers]' binding is really just supposed to be a convenience if you aren't going to be also adding other layers using ```[leafletLayers]```.

If you use ```[leafletLayers]```, you can also configure the ```[leafletLayersControl]``` and ```[leafletLayersControlOptions]``` to indicate which layers can be turned on/off by the user and configure the control itself.

As a side note - the only other options you have to provide up front are the zoom/center. The other options have reasonable defaults that will be used.

If you want to provide some base layers and then dynamically add some other layers, you probably want something like:

component.html
```html
<div leaflet style="height: 300px;"
     [leafletOptions]="options"
     [leafletLayers]="layers"
     [leafletLayersControl]="layersControl"
     (leafletMapReady)="initMap($event)">
</div>
```

component.ts
```js
// the 'as any' is only needed if you're getting a type mismatch error
layers: L.Layer[ L.geoJSON(this.geodata as any) ];
layersControl = { baseLayers: { ... } };
options = {
	zoom: 10,
	center: L.latLng([ 46.879966, -121.726909 ])
};
```

You should also check out the demo. The third example shows how to have multiple layers that you can turn on and off either using the layers control or by updating the layers array.

**Comment by reblace** [comment]
I also just pushed some improvements to the README and added a geoJSON example to the demo application.

**Comment by reblace** [comment]
I'm gonna close this as I think I provided enough detail to get you going. Let me know if you run into any specific issues. Thanks!

**Comment by unnieayilliath** [comment]
Is there any sample available on using GeoJSON layers in ngx-leaflet . The snippet provided is very basic and does not give much information

**Comment by reblace** [comment]
The demo has an example in this file:
https://github.com/Asymmetrik/ngx-leaflet/blob/master/src/demo/app/leaflet/layers/layers-demo.component.ts

The README has some instructions on how to run the demo locally.

The basic idea is that anything that extends layer can be added to the array of layers bound to the leafletLayers input binding. So, you can create geoJSON layers and add them to that array and it should all work fine. That demo example just shows how to create a bunch of different kinds of layers and add them all to the map using the leafletLayers array input binding.

**Comment by sphil375** [comment]
When I added GeoJSON with 'Point' to ngx-leaflet array as shown in 'layers-demo.component.ts', the images are not showing in the map(marker-icon.png is failed to get loaded). Could you please help me. Please find below the code that I tried:

 this.geoJSONArray.push({
	 id: spot.properties.OBJECTID,
	 name: spot.properties.NAME,
	 enabled: true,
	 layer: geoJSON(
	 ({
	 "type": "Point",
	 "coordinates": spot.geometry.coordinates
	 }) as any,
	 {style: () => ({
	   "color": "#00ff00",
	   "weight": 5,
	   "opacity": .75
	 })}
	   , {
		 icon: icon({
		   iconSize: [ 25, 41 ],
		   iconAnchor: [ 13, 41 ],
		   iconUrl: 'assets/marker-icon.png',
		   shadowUrl: 'assets/marker-shadow.png'
		 })
	   })
   });
-------
The icon object I added later as previous version is not worked. Please help me
