### ISSUE TITLE
leaflet-webgl-heatmap plugin with angular2-leaflet

### ISSUE THREAD

**Issue by giricgoyal** [bluehalo/ngx-leaflet#47]
Hi 

I am trying to get leaflet plugins (leaflet-webgl-plugin) to get to work with angular 2 and leaflet. But unsuccessful. Any ideas?

http://ursudio.com/webgl-heatmap-leaflet/

**Comment by reblace** [comment]
The README contains details about how to get a reference to the L.Map instance. With a reference, you can do whatever you need with the map (like add a customer layer or plugin).

You can also check out several other plugins that demonstrate how to extend the functionality of this plugin if you'd like to build your own ng2 plugin:

https://github.com/Asymmetrik/angular2-leaflet-draw
https://github.com/Asymmetrik/angular2-leaflet-filter
https://github.com/Asymmetrik/angular2-leaflet-markercluster
https://github.com/Asymmetrik/angular2-leaflet-d3

**Comment by reblace** [comment]
Gonna close this unless you have any specific issues with the plugin. Thanks!
