### ISSUE TITLE
get coordinates on click?

### ISSUE THREAD

**Issue by arahmanali** [bluehalo/ngx-leaflet#51]
i want to get coordinates on map click.
TIA

**Comment by reblace** [comment]
Check out the section of the README on "Getting a Reference to the Map". Once you have a reference to the map, you can register an event handler on the map click event. http://leafletjs.com/reference-1.0.3.html#map-event

```js
map.on('click', () => { console.log(e.latlng); });
```

I'll probably eventually add an event handler directive at some point, but in the interim you can do it directly.

**Comment by reblace** [comment]
I think everything's addressed. Let me know if you have any other issues.

**Comment by d3rrick** [comment]
Thanks alot

**Comment by hp1361** [comment]
Hi
How to use the component click event for get coordinate : (leafletClick)

**Comment by reblace** [comment]
The (leafletClick) output binding emits a `LeafletMouseEvent` - https://leafletjs.com/reference-1.3.2.html#mouseevent

It should have a latlng accessible in the object that represents the location clicked.
