### ISSUE TITLE
Is it possible to show markers as bubbles and the bubble size will depend on the value of specific object?

### ISSUE THREAD

**Issue by amalshehu** [bluehalo/ngx-leaflet#52]
![image](https://cloud.githubusercontent.com/assets/12576673/26550749/cbcdd224-449c-11e7-9a57-89dc7311ef01.png)
Object structure
var marker ={
"lat":78.99,
"lng":-23.44,
"value": 252
}

**Comment by amalshehu** [comment]
@gharibi Any help?

**Comment by reblace** [comment]
You have a lot of options here.

1. You can draw your own circles on the map. Generate your shapes and add them to a layer and add the layer to the map.

2. @asymmetrik/angular2-leaflet-d3 can help you draw a grid of hexbins on the map. And you can size the hexbins based on a dimension of the data. That plugin will probably eventually have other ways to bind drawn shapes on the map to data in the future.

3. There are a lot of other plugins and ways to draw on the map, and if you get a reference to the map using the methods described in the README, you should be able to use any of them to do what you want.

**Comment by gharibi** [comment]
@amalshehu I would go for `@asymmetrik/angular2-leaflet-d3` as you can take advantage of powerful visualization capabilities of D3.

**Comment by amalshehu** [comment]
Thanks for both. It's so  fast response. I will try it and get back.

**Comment by gharibi** [comment]
@amalshehu I am working on an example for Angular2-leaflet to work with WMS & WFS layers. So far I have implemented something which can help you as well. I have added this as part of my `ngOnInit` in my `component.ts':
```
        var yourLayer = L.TheLoadMethod(YourLayerURL, {
            style: function(feature) {
                switch (feature.properties['YourDistinctFieldName']) {
                    case 'value1': return {
                                            radius: 5,
                                            ...
                                        };
                    case 'value2': return {
                                            radius: 10,
                                            ...
                                        };
                        ...           
                }
            }            
        }).addTo(myMap); 
```
The `LoadMethod` could be `L.tileLayer` for example. You can see more info in here: [http://leafletjs.com/reference-1.0.3.html](url)

This is also align with solution no. 1 from @reblace .

**Comment by amalshehu** [comment]
I integrated angular2-leaflet-d3 in my application. Ok, I will check it out. @gharibi

**Comment by amalshehu** [comment]
@gharibi  As per your instruction I  used an example from @asymmetrik/angular2-leaflet-d3.There was a ping demo.In that random coordinates are generated.But i want make it work with my existing data.So it will be helpful if you provide sample code if available.Thanks

**Comment by amalshehu** [comment]
![peek 2017-05-30 16-54](https://cloud.githubusercontent.com/assets/12576673/26581130/caeae93e-4558-11e7-8b6f-e37914e49add.gif)
My current situation

**Comment by amalshehu** [comment]
![image](https://cloud.githubusercontent.com/assets/12576673/26581287/761466be-4559-11e7-8032-c73a2a865b1c.png)
I would like to make something like this.

**Comment by gharibi** [comment]
@amalshehu your example based on `@asymmetrik/angular2-leaflet-d3` is really nice, tho. Anyway, you can implement the second example according to what I wrote earlier. 

Surely I can share the code. I will coordinate that with @reblace to see how we that example can be shared on `angular2-leaflet`.

**Comment by amalshehu** [comment]
@gharibi Amazing!

**Comment by amalshehu** [comment]
![image](https://cloud.githubusercontent.com/assets/12576673/26617209/805ebd34-45f1-11e7-8ca1-333e59085cab.png)
Hi, I made it working, used the onMapReady function to get the instance and made the changes.I would like the subroads, yellow triangles from my map.Any suggestion on best practices? @gharibi @reblace

**Comment by amalshehu** [comment]
Fixed it.Used mapbox :+1:

**Comment by reblace** [comment]
Awesome, yeah I was gonna suggest a custom map with mapbox

**Comment by reblace** [comment]
Sounds like everything was addressed. Feel free to comment if there are any other issues.
