### ISSUE TITLE
Fails on rollup build 

### ISSUE THREAD

**Issue by amalshehu** [bluehalo/ngx-leaflet#54]
I'm geting these following erorrs on rollup aot build.
```
dist/tmp/app/home/demo/leaflet-d3/ping/ping-demo.component.js (23:21) 'tile
Layer' is not exported by 'node_modules/leaflet/dist/leaflet-src.js'
dist/tmp/app/home/demo/leaflet-d3/ping/ping-demo.component.js (41:22) 'latL
ng' is not exported by 'node_modules/leaflet/dist/leaflet-src.js'
dist/tmp/app/home/demo/leaflet-d3/ping/ping-demo.component.js (68:31) 'circ
le' is not exported by 'node_modules/leaflet/dist/leaflet-src.js'
node_modules/@asymmetrik/angular2-leaflet/dist/leaflet/core/leaflet.directive.js (6:32)
'latLng' is not exported by 'node_modules/leaflet/dist/leaflet-src.js'
node_modules/@asymmetrik/angular2-leaflet/dist/leaflet/core/leaflet.directive.js (20:21)
 'map' is not exported by 'node_modules/leaflet/dist/leaflet-src.js'
node_modules/@asymmetrik/angular2-leaflet/dist/leaflet/layers/control/leaflet-control-la
yers.wrapper.js (13:31) 'control' is not exported by 'node_modules/leaflet/dist/leaflet-
src.js'
```

**Comment by reblace** [comment]
I was able to run 'gulp build' using a clean installation of npm dependencies and the build passed on MacOS. I'm using Node 6.9, npm 3.10. The only global node dep is gulp. The Travis CI build also passes on master.

Can you provide more context? What OS are you on? Are you sure you don't have something weird going on with your node modules? You were also having issues before with the leaflet typings, that seem to be specific to your setup.

**Comment by amalshehu** [comment]
Node 7.10.0
npm 4.2.0
OS: Ubuntu 16.10

I found one more thing. This is not the issue with angular2-leaflet. The leaflet is not exporting the map, control, latLng on rollup build.I think the dist/leaflet-src.js is in Es5.

**Comment by reblace** [comment]
are you building against leaflet 0.7 or 1.x?

**Comment by amalshehu** [comment]
Leaflet 1.0.3

**Comment by reblace** [comment]
I honestly have no idea the issues you're having with typings. I can't reproduce it. If you get any further diagnosing it, let me know.

**Comment by amalshehu** [comment]
I know its very difficult for you to find the issue.I have integrated angular2-leaflet with fresh seed.Still has the same issue.If you got time, take a look into it.
https://github.com/amalshehu/angular2-seed-leaflet

**Comment by reblace** [comment]
I cloned that repo and did 

```
yarn install
npm start
```

And it launched the browser and showed me a map. Does that fail to compile for you?

**Comment by reblace** [comment]
What do you get when you run this command (should list all globally installed dependencies)?

```
npm ls -g --depth 0
```

I get the following:
```
/username/.nvm/versions/node/v6.9.5/lib
├── @angular/cli@1.0.0
├── bunyan@1.8.5
├── gulp@3.9.1
├── npm@3.10.10
├── typescript@2.3.3
└── yarn@0.24.5
```

**Comment by amalshehu** [comment]
The problem was with the rollup build.When I `run npm run build.prod.rollup.aot ` those above errors began to appear.But I fixed the issue.The problem was with named exports. leaflet-src.js was not exporting the required modules.So i added the missing things named exports in project.config.ts.
```
this.ROLLUP_NAMED_EXPORTS = [
      ...this.ROLLUP_NAMED_EXPORTS,
      {'node_modules/leaflet/dist/leaflet.js': [  'leaflet' ]},
      {'node_modules/leaflet/dist/leaflet-src.js': [  'latLng', 'map','control' ]},

    ];
```
Now its working as expected.

**Comment by amalshehu** [comment]
Thanks for your support. angular2-leaflet is an amazing plugin.Good work friend. @reblace

**Comment by reblace** [comment]
Oh yeah, Webpack has something similar. Glad you were able to figure it out!
