### ISSUE TITLE
Leaflet popup actions

### ISSUE THREAD

**Issue by dima12qw** [bluehalo/ngx-leaflet#55]
Is there any possibility to render with the html content of a popup? For example to implement data binding (ngFor ,ngIf,ngmodel). I want to implement a form for every marker popup,and I don't know how to take the values of the form

**Comment by reblace** [comment]
I'm not sure. I've never tried that specifically. You could probably play a trick where you show and move an ng2 html form when you click on the marker (and suppress the default marker popup). I'm pretty sure you can hook into the marker events to manage it.

**Comment by reblace** [comment]
Not directly related to the angular2 leaflet plugin. Gonna close this issue.
