### ISSUE TITLE
Using with esri-leaflet

### ISSUE THREAD

**Issue by jessenic** [bluehalo/ngx-leaflet#61]
I've been trying to use [esri-leaflet](https://github.com/Esri/esri-leaflet) with angular2-leaflet and Angular CLI but without success.

I've installed esri-leaflet 2.0.8 and types/esri-leaflet 2.0.0 packages.
I added
`import 'esri-leaflet';`
to my map component and in the onMapReady function added
`L.esri.basemapLayer("Topographic").addTo(map);`

ng build compiles without any errors, but during runtime L.esri is undefined.

Any ideas?

**Comment by dskg1986** [comment]
Sorry if this is too much text or if I am late in answering this.  Hopefully this helps.  I have multiple basemaps and I add a controller so a user can switch to whatever basemap they want.

I am using angular4 and I handled this by importing leaflet and esri-leaflet like so

`
import * as L from 'leaflet';
import * as esri from 'esri-leaflet';
`

Then in a mapInit() or ngOnInit() you can use just "esri" (remove "L.") to define your basemaps.

`
ngOnInit() {
		var topoMap = esri.basemapLayer("Topographic"),
			usaTopo = esri.basemapLayer("USATopo"),
			streetMap = esri.basemapLayer("Streets"),
			imageMap = esri.basemapLayer("Imagery"),
			grayMap = esri.basemapLayer("Gray");

		var baseMaps = {
			"Satelite" : imageMap,
			"Streets": streetMap,
			"Topographic": topoMap,
			"USA Topo" : usaTopo,
			"Gray" : grayMap
		};
		
		var myMap = L.map('mapid', {
				center : [39.754264, -105.002441],
				zoom : 13,
				layers: [topoMap]
		});
		
		L.control.layers(baseMaps).addTo(myMap);
	}
`

**Comment by dskg1986** [comment]
I don't like that I had to import both esri-leaflet and leaflet.  I am going to continue working on this and see if I can come up with a cleaner solution.

**Comment by reblace** [comment]
If you're still having issues, feel free to post a more detailed description and I can try to reproduce it. Normally, what you did works cause the ```import 'esri-leaflet';``` statement is enough to make webpack include that module. However, global packages (like leaflet and d3) need to be configured via the provider plugin:

```
new webpack.ProvidePlugin({
	L: 'leaflet'
})
```

But, I'm not sure how plugins are handled in angular cli.

If you don't do the plugin, it's possible that the esri-leaflet plugin is not finding the ```L``` global variable or has its own scoped ```L``` and therefore it isn't being added to the ```L``` reference you're using.

As an aside, there's nothing unusual about having to import leaflet and then importing the package that depends on Leaflet, even if you're not using leaflet directly. E.g.:

```
import * as L from 'leaflet';
import 'esri-leaflet';

let esriLayer = L.esri.basemapLayer("Topographic");
```

**Comment by reblace** [comment]
Gonna close this since I haven't heard back. Lemme know if there are further issues.
