### ISSUE TITLE
Quickstart issue

### ISSUE THREAD

**Issue by sbrshk** [bluehalo/ngx-leaflet#65]
Hello.

When trying to use this component in angular project, there appears following problem: map is shown as separated square pieces covering random screen space (as st the screenshot below).

![screenshot](https://user-images.githubusercontent.com/22587443/28609043-ac605656-71eb-11e7-82e2-938b58ed4ac0.png)

The LeafletModule is imported in the work module as it is described in README. The component itself has been taken from the [Basic Map Setup](https://github.com/Asymmetrik/angular2-leaflet#basic-map-setup) as is.

The markup of the app is built on the Bootstrap grid base. Leaflet is located within a col-md-.. div, but goes out of its scope.

So, what can cause such a problem? 

Thank you

**Comment by probadb** [comment]
i had the same problem when somehow it didn't load leaflet css properly. Double check it's loading `node_modules/leaflet/dist/leaflet.css`

**Comment by sbrshk** [comment]
@probadb yeah, thank you! I already figured it up. There was a problem with alignment and padding.
