### ISSUE TITLE
How can I integrate with Leaflet Routing Machine? {question}

### ISSUE THREAD

**Issue by justmatt25** [bluehalo/ngx-leaflet#66]
I am trying to add the Leaflet Routing Machine control in my Angular 4 project but I am not sure how to do it. I tried declaring the route I wanted in the template and then binding to the "[leafletLayersControl]" but that didn't seem to work.

**Comment by reblace** [comment]
I've never used that plugin before, but the easiest way to start would be to register for the map ready callback and then manually add the Routing Machine control to the map just like you would if you weren't using Angular.

A more advanced way would be to extend the angular2-leaflet directive.

I believe each is discussed a bit in the README.

**Comment by justmatt25** [comment]
Thanks so much for your help! I will look into doing that. I already was using the map ready callback so I will try to just add it on to that function.
Thanks again!
