### ISSUE TITLE
Error 404

### ISSUE THREAD

**Issue by Nomaq** [bluehalo/ngx-leaflet#67]
Hi 

i have this error if anyoine can help me 

localhost:3000/@asymmetrik/angular2-leaflet Failed to load resource: the server responded with a status of 404 (Not Found)
localhost/:30 Error: Fetch error: 404 Not Found
  Instantiating http://localhost:3000/@asymmetrik/angular2-leaflet
  Loading http://localhost:3000/app/mobile-content/mobile-content.module.js
  Loading http://localhost:3000/app/app.module.js
  Loading http://localhost:3000/app/main.js
  Loading app
    at fetch.js:37
    at ZoneDelegate.invoke (zone.js:391)
    at Zone.run (zone.js:141)
    at zone.js:818
    at ZoneDelegate.invokeTask (zone.js:424)
    at Zone.runTask (zone.js:191)
    at drainMicroTaskQueue (zone.js:584)

**Comment by reblace** [comment]
Can you give more details about your setup? It looks like your app is using a loader to try to load all the source files and it fails when it tries to get the angular2-leaflet dependency.

Is this error in the browser? Or is it when it's building on the server?

**Comment by reblace** [comment]
No response, and I think this issue is build/project related.
