### ISSUE TITLE
why the picture is Not joined together

### ISSUE THREAD

**Issue by Huang9495** [bluehalo/ngx-leaflet#69]
**## Issue:** I add the leaflet into angualr2 from the official tutorial and I change the coordinate to Melbourne.after i initiate the angular2, the map is  not joined together
**## Environment**
Ubuntu:14.04,angular2,

![screenshot from 2017-08-20 09 51 06](https://user-images.githubusercontent.com/26674689/29491422-2efd2c00-858e-11e7-966e-799bb041a4e9.png)
It is what happen?Who can tell me

**Comment by reblace** [comment]
This is usually a symptom of the CSS file not being loaded.

Check the README section (excerpt below) about how to ensure the leaflet.css file is being properly loaded by your application.

### Import the Leaflet Stylesheet
For leaflet to work, you need to have the leaflet stylesheets loaded into your application.
If you've installed via npm, you will need to load ```./node_modules/leaflet/dist/leaflet.css```. 
How you include the stylesheet will depend on your specific setup. Here are a few examples:

#### Direct Import from HTML
If you are just building a webpage and not using a bundler for your css, you'll want to directly import the css file in your HTML page.

```html
<head>
	...
	<link rel="stylesheet" type="text/css" href="./node_modules/leaflet/dist/leaflet.css">
	...
</head>
```

#### Configuring Webpack Style Loaders
If you are using Webpack, you will need to import the css file and have a style-loader configured.
You can use the demo included in this application as a reference.

Generally, in ```vendor.ts```:
```ts
import 'leaflet/dist/leaflet.css';
```

And then in your webpack config file:
```js
{
    ...
    "module" : {
		loaders: [
		    ...
		    { test: /\.css$/, loaders: [ 'style-loader', 'css-loader' ] },
		    ...
		]    
    },
    ...
}
```


#### Adding Styles in Angular CLI
If you are using Angular CLI, you will need to add the Leaflet CSS file to the styles array contained in ```.angular-cli.json```

```js
{
    ...
    "apps": [
        {
            ...
        	"styles": [
                "styles.css",
                "../node_modules/leaflet/dist/leaflet.css"
            ],
            ...
        }
    ]
    ...
}
```

Let me know if you have any other questions and thanks for using the plugin!

**Comment by Huang9495** [comment]
Hi！ @reblace  I have resolved the issue. I have done step as you said. Now I can see the map the whole world . The reason of the issue is my internal storage of my computer and the network .After I sweep the trash of my computer .The map is OK! Thank you for you help !

**Comment by reblace** [comment]
got it working
