### ISSUE TITLE
/node_modules/@types/leaflet/index.d.ts gives errors on compile

### ISSUE THREAD

**Issue by pmeems** [bluehalo/ngx-leaflet#73]
I've added this module to my Angular v4.3.6 application.
When I add `LeafletModule.forRoot()` to my imports in `app.modules.ts` and recompile I get lots of errors in `/node_modules/@types/leaflet/index.d.ts`
The first few are:
- `/node_modules/@types/leaflet/index.d.ts` (583,56): ',' expected.
- `/node_modules/@types/leaflet/index.d.ts` (583,104): Expression expected.
- `/node_modules/@types/leaflet/index.d.ts` (585,36): '(' expected.

When I open this file in my IDE (WebStorm v2017.2.3) it also reports these errors.
Mostly `TS1005` and `TS1109`.

I also downloaded the zip from github of the `dev` and `master` branch and I can run the demos.
In my application, I don't use `gulp`, so I assume I need to reconfigure something.
I run `ng serve` to compile and run my application.

I tried Googling but couldn't find a solution.
I already excluded my node_modules in my `tsconfig.json`
Other specs:
- Window10
- nmp v4.3.0
- node v6.9.5
- tsc v1.0.3.0

Any help is much appreciated.

**Comment by reblace** [comment]
The ```@types/leaflet``` errors you're seeing might be a result of typescript version differences. The latest change to the leaflet package typings (v1.2) made some changes that caused errors in my build also until I switched to use at least Typescript 2.3.

What's your package.json look like? If you can't upgrade to tsc 2.3, you could try changing your ```@types/leaflet``` and ```leaflet``` to slightly older versions (e.g., 1.0 or 1.1).

**Comment by pmeems** [comment]
In my PATH I still had an old reference to tsc v1. That's why the old version number was shown.
I removed the path and updated to v2.5.2 (I was already on v2.2).
Next I ran `ncu` on my project and updated all packages to their last stable version.
Then I ran `npm update` and I now have a map on my page!
Thanks for your assistance.

For future reference, here's my package.json:
`{
  "name": "..",
  "license": "MIT",
  "version": "0.0.1",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/common": "^4.0.0",
    "@angular/compiler": "^4.0.0",
    "@angular/core": "^4.0.0",
    "@angular/forms": "^4.0.0",
    "@angular/http": "^4.0.0",
    "@angular/platform-browser": "^4.0.0",
    "@angular/platform-browser-dynamic": "^4.0.0",
    "@angular/router": "^4.0.0",
    "@asymmetrik/angular2-leaflet": "^2.2.1",
    "angularfire2": "^4.0.0-rc.2",
    "bootstrap": "^3.3.7",
    "core-js": "^2.4.1",
    "firebase": "^4.0.0",
    "leaflet": "^1.2.0",
    "rxjs": "^5.1.0",
    "typescript": "^2.5.2",
    "zone.js": "^0.8.17"
  },
  "devDependencies": {
    "@angular/cli": "1.3.2",
    "@angular/compiler-cli": "^4.0.0",
    "@types/jasmine": "2.5.54",
    "@types/node": "~8.0.26",
    "codelyzer": "~3.1.2",
    "jasmine-core": "~2.8.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~1.7.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-coverage-istanbul-reporter": "^1.3.0",
    "protractor": "~5.1.0",
    "ts-node": "~3.3.0",
    "tslint": "~5.7.0",
    "typescript": "~2.5.2"
  }
}
`

Sorry for the strange formatting, can't get it to work properly on GitHub.
