### ISSUE TITLE
Reload Map and multiple maps in the same page

### ISSUE THREAD

**Issue by Oscarsgc** [bluehalo/ngx-leaflet#75]
I'm creating a dashboard with draggable maps. The fact is that when i drag a new map, the dashboard refreshes and the old map dissapears, i just can see the markers in the first map, and the recently created map doesn't loads anything. The first map works when i refresh the page (F5) but the second doesn't appears... and something that i noticed is that when I zoom in the second map, the zoom affects the first map... Do you have any Idea on what's going on?? how can I use multiple maps in the same page? How can I reload the coordinates from options or my entire map??

I'm uploading some pictures to clarify

![screen shot 2017-09-05 at 9 20 23 am](https://user-images.githubusercontent.com/4324370/30063141-a0833cb8-921b-11e7-838f-77a3e013f1a1.png)
In this picture, you can see my map working correctly

![screen shot 2017-09-05 at 9 20 38 am](https://user-images.githubusercontent.com/4324370/30063174-c6cbf52c-921b-11e7-93d5-84a8695a3803.png)
This is what happens when I add another map, both maps seems not to be present

![screen shot 2017-09-05 at 9 20 51 am](https://user-images.githubusercontent.com/4324370/30063196-dfec3864-921b-11e7-8286-1c7f7d0cde49.png)
When I refresh the entire page, the first map loads, please check the map markers, they are correctly positioned in this picture

![screen shot 2017-09-05 at 9 21 14 am](https://user-images.githubusercontent.com/4324370/30063235-03bf7030-921c-11e7-87ac-2106c5455e54.png)
I zoomed a bit in the second map and guess what? The first map got zoom and my markers changed their location...

**Comment by reblace** [comment]
Do you have your component and template code that you could share?

One thing that can cause this behavior is if you reuse the same Layers between multiple maps.
Generally with Leaflet, a layer can only be added to one map (including baselayers). This just means you need to recreate your baselayers for each map.

**Comment by Oscarsgc** [comment]
Well, maybe that's the problem... i'm creating new maps with the same tileLayer... I obtain my map options like this 
```javascript
options: {
      layers: [
        L.tileLayer('https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png',
          {
            maxZoom: 15,
            subdomains: 'abcd'
          })
      ],
      zoom: 5,
      center: L.latLng([this.mapCenters['Center'].mapCenterLatitude, this.mapCenters['Center'].mapCenterLongitude])
    }
```
For each new map, options are the same... any idea on how can i make a small variation or how can i fix this?

**Comment by reblace** [comment]
A lot of times what I do in this situation is create an array or map of "map specs" in my component and each map spec is an object that contains everything the map needs like options, layers, etc. That way, when I want to add a new map, I add a new map spec to the array or map.

**Comment by Oscarsgc** [comment]
@reblace can you please give me an example? The fact is that i need to use the same map, maybe with another latitude and longitude, and different markers that i will obtain from a service, and well the tile I'm using is the one that i need...

**Comment by Oscarsgc** [comment]
@reblace nevermind, i just make it work! Thanks for the support, great job with the library!

**Comment by philglen** [comment]
@Oscarsgc I am facing this same issue, how did you make it work?

**Comment by sebastienpattyn93** [comment]
@Oscarsgc @reblace @philglen I'm having the same issue. I have two components, that are each showing a map, but with different overlays. they both want to use the same baselayer, but for some reason it is not possible to have the radio button of the base layer selected on both the maps, when I select the baselayer on the second leaflet map, it gets unselected on the first one. my code looks like this on both the components:

##### leaflet-test.html
```
<div
        style="height: 600px;width: 100%"
        leaflet
        [leafletOptions]="options"
        [leafletLayersControl]="layersControl"
      ></div>
    </div>
```

##### lealfet-test.ts
```
 baselayer = tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    maxZoom: 20
  });
  public options = {
    layers: [this.baselayer],
    zoom: 14,
    scrollWheelZoom: false
  };

  layersControl = {
    baseLayers: {
      Map: this.baselayer
    }
  };
```

**Comment by reblace** [comment]
@sebastienpattyn93 The issue is almost always that you're reusing the same layer object for both maps. You have to create unique layers for each map and keep them separate.

Layers are mutated by the map to which they are added, so they are tied to that map. You get these weird cross-map interactions when you try to reuse them.

**Comment by strarsis** [comment]
@reblace: Let's say two Leaflet maps should use the same layer (and are synced).
When only one map can be used per layer, two of these layers have to be used.
When the same tile provider is used, wouldn't this result in two HTTP requests, one being unnecessary?
