### ISSUE TITLE
Move to leaflet 1.1 and start using es6 imports?

### ISSUE THREAD

**Issue by chriszrc** [bluehalo/ngx-leaflet#77]
Hi, 

My understanding is that with leaflet's recent move to es6 imports (http://leafletjs.com/2017/06/27/leaflet-1.1.0.html), that we could potentially not have to include the entire leaflet library in our builds. I have confirmed that I can indeed now do : 

`import { Map } from 'leaflet';`

But I haven't confirmed yet that if I update everything, I would get a more compact leaflet build. And obviously I then want to use this wonderful library, and my understanding is that if any lib does a : 

`import * as L from 'leaflet';`

we won't see any of those size reductions. Thoughts?

**Comment by reblace** [comment]
I have a couple more pressing work tasks atm, but it's basically next on my list of maintenance things to do.

**Comment by reblace** [comment]
I made a branch that converts everything to use targeted imports.
/moduleLeaflet

I haven't gotten very far with it yet, but when I ran the demo (gulp dev), it didn't seem to tree shake out the unused stuff. So, there's a bit more digging to be done. Just giving you a heads up if you wanted to mess around with that branch as well.

**Comment by chriszrc** [comment]
Hmm, I'm not seeing uglifyjs being used here, I don't think you would see tree-shaking unless you had this configured:

https://webpack.js.org/guides/tree-shaking/

Or if you were pulling in the library and using the angular cli, which does something similar afaik-

**Comment by reblace** [comment]
Targeted imports were introduced for 2.5.x. I still haven't had any success getting projects that use leaflet to successfully tree shake, but at least now the library is compatible.

**Comment by reblace** [comment]
Closing this now since the library is doing targeted imports
