### ISSUE TITLE
map projection: need advise

### ISSUE THREAD

**Issue by pmeems** [bluehalo/ngx-leaflet#78]
I want to use several base layers which have different projections.
So when I switch a base layer the map projection should change and the vector layer should re-get its data sending the new map projection.
Is this possible? How can I add the projection to the base layer object and is a change event emitted when the base layer is changed and will it also broadcast the projection?

**Comment by reblace** [comment]
I'm guessing the answer is no based on this: https://github.com/Leaflet/Leaflet/issues/2553
It sounds like you'd need to use [hidden] or ngIf to show/hide alternating maps. 

I'd recommend trying to get it working in just Leaflet and then see if you can get it working in ngx-leaflet.

**Comment by reblace** [comment]
I'm gonna close this. Feel free to add more details if you find a solution, or open a new issue if you determine there is a defect with ngx-leaflet that needs to be fixed. Thanks!
