### ISSUE TITLE
How do I Fly to a point?

### ISSUE THREAD

**Issue by tiggertag** [bluehalo/ngx-leaflet#79]
Hi,

I am new to using leaflet and ngx plugin. How can I get the map to fly to a particular location on a button click, which is outside the map. I see the leaflet has a method called "flyTo". How do I do this using this plugin. I am using this in typescript with typings project. Thanks!

**Comment by tiggertag** [comment]
I figured it out. Used onMapReady event callback to get the map reference and used it in the button's click event to call flyTo method.

**Comment by reblace** [comment]
Your approach will work just fine. You can also use the input bindings to move the map and configure the move animations.

The ones you could look at include ```leafletZoom ```,  ```leafletCenter ```, and/or ```leafletFitBounds``` input bindings. These cause the map to move to the new location. When moves are initiated, it uses move options that are either default or determined by ```leafletFitBoundsOptions```, ```leafletPanOptions```, ```leafletZoomOptions```, or ```leafletZoomPanOptions```

Thanks for using the plugin!
