### ISSUE TITLE
leaflet heatmap

### ISSUE THREAD

**Issue by vaydich** [bluehalo/ngx-leaflet#80]
Hello!
I want to include heatmap plugin for leaflet in my angular 2 project http://www.patrick-wied.at/static/heatmapjs/example-heatmap-leaflet.html
But i don't now how. 
Can you help me with my problem&

**Comment by diegobrum** [comment]
+1

**Comment by reblace** [comment]
I'll probably build an extension that makes it easy to do it directly. But, in the interim, you can use one of the methods described in the README for getting a handle to the map and adding the heatmap yourself.

https://github.com/Asymmetrik/ngx-leaflet#getting-a-reference-to-the-map

Once you have a map reference, you can add the heatmap layer and manipulate it directly.

**Comment by vaydich** [comment]
Thank you. I got it about reference. 
But my question also is how i should include heat map js file in my project? If i include it directly in angular cli json file like this:

```
"scripts": [
        "../node_modules/bootstrap/dist/js/bootstrap.js",
        "./assets/js/heatmap.js"
      ]
```

i see an error before i start to use it somehow:

```
VM41926:243 Uncaught ReferenceError: L is not defined
    at eval (eval at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9), <anonymous>:243:1)
    at eval (<anonymous>)
    at webpackJsonp.../../../../script-loader/addScript.js.module.exports (addScript.js:9)
    at Object.../../../../script-loader/index.js!../../../../../src/assets/js/heatmap.js (heatmap.js?a80d:1)
    at __webpack_require__ (bootstrap 380c181…:54)
    at Object.2 (scripts.bundle.js:82)
    at __webpack_require__ (bootstrap 380c181…:54)
    at webpackJsonpCallback (bootstrap 380c181…:25)
    at scripts.bundle.js:1
```

**Comment by reblace** [comment]
In webpack you'd normally use the provide plugin to make the L global variable available to all modules. I'm not sure how to get this working with the CLI, though.

What's likely happening is that heatmap.js is referencing ```L```, but Webpack isn't loading leaflet into the heatmap.js module. So, no L is defined when that code is evaluated.

**Comment by reblace** [comment]
https://github.com/Asymmetrik/ngx-leaflet-tutorial-3rd-party-libs

Contains a working example of using heatmap with angular cli.

**Comment by reblace** [comment]
Closing this as resolved as the listed example provides a demonstration of how to use heatmap.js with ngx-leaflet

**Comment by shashi5678** [comment]
Heat is not working if two maps are on same page
