### ISSUE TITLE
reload map

### ISSUE THREAD

**Issue by Landay7** [bluehalo/ngx-leaflet#81]
Hello! How can I change leaflet options and reload map? 
My code 
public options = {
      layers: [
          //L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '...' })
          L.tileLayer('assets/img/{z}/'+this.floor+' [www.imagesplitter.net]-{y}-{x}.jpeg', { maxZoom: 3, attribution: '...' })
      ],
      zoom: 1,
      center: L.latLng([ 46.879966, -121.726909 ]),
      crs: L.CRS.Simple
  };

Button 
<button (click)="next()" style="position: absolute; right: 50px;">Next</button>

Button event
public next(){
      this.floor += 1;
        this.options.layers =  [
              //L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 18, attribution: '...' })
              L.tileLayer('assets/img/{z}/'+this.floor+' [www.imagesplitter.net]-{y}-{x}.jpeg', { maxZoom: 3, attribution: '...' })
          ];
  }
Can you help, please?

**Comment by reblace** [comment]
If you are just trying to switch between baselayers, you can do this by simply changing which layers are in the bound layers array.

```js
public options = {
    zoom: 1,
    center: L.latLng([46.879966, -121.726909]),
    crs: L.CRS.Simple
};

this.layers: L.Layer[] = [ L.tileLayer('assets/img/{z}/'+this.floor+' [www.imagesplitter.net]-{y}-{x}.jpeg', { maxZoom: 3, attribution: '...' }) ];

public next(){
    this.floor += 1;
    this.layers = [ L.tileLayer('assets/img/{z}/'+this.floor+' [www.imagesplitter.net]-{y}-{x}.jpeg', { maxZoom: 3, attribution: '...' }) ];
}

```

And then you bind the layers array to the ```[leafletLayers]``` input.
```html
<div leaflet style="height: 300px;"
     [leafletOptions]="options"
     [leafletLayers]="layers">
</div>
```

**Comment by reblace** [comment]
Closing this unless there are any follow on questions.
