### ISSUE TITLE
how to position zoom control?

### ISSUE THREAD

**Issue by lhammond** [bluehalo/ngx-leaflet#85]
i've tried a number of things .. is it supported?

if not, where should I add this and PR?

**Comment by reblace** [comment]
In your map options, set ```zoomControl``` to ```false```.
And then add your own zoom control to the map in the ```leafletMapReady``` callback.

E.g.,

```js
options = {
	layers: L.tileLayer('http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', { maxZoom: 10, attribution: '...' }),
	zoom: 5,
	zoomControl: false,
	center: L.latLng(46.879966, -121.726909)
};

mapReady(map: L.Map) {
	map.addControl(L.control.zoom({ position: 'bottomright' }));
}
```

```html
<div leaflet style="height: 300px;"
        [leafletOptions]="options"
        (leafletMapReady)="mapReady($event)">
</div>
```

There really isn't a good way to do this otherwise. They removed the zoomControl accessor in Leaflet 1.0.

**Comment by reblace** [comment]
Gonna close this unless there are any follow-up questions.

**Comment by bbbneo333** [comment]
Is it still the only way to do this?

**Comment by juserror** [comment]
I'd say there is no need for setting zoomControl: false in options. Maybe slightly cleaner without the need for importing * as L.


.ts file
```
import { Map, Control , etc. } from "leaflet";

private map: Map;
private control: Control;

// other code

onMapReady(map: Map) {
        this.control = map.zoomControl;
        map.addControl(this.control.setPosition('topright'));
}
```

.html file
```
<div class="map" leaflet [leafletOptions]="options" 
[leafletBaseLayers]="baseLayers" (leafletMapReady)="onMapReady($event)"></div>
```

**Comment by volago** [comment]
Have anyone tried that attempt? It's no working for me, but according to docs it should

.ts
```typescript
export class MapComponent implements OnInit {
[...]
  zoomOptions: Control.ZoomOptions = {
    position: 'bottomleft'
  };
[...]
}
```
.html
```html
<div [style]="style" leaflet [leafletOptions]="leafletOptions" [leafletLayers]="leafletLayers"
  [leafletZoomOptions]="zoomOptions"></div>
```

@juserror When I don't set zoomControl: false in options, then second control panel appear on the map
