### ISSUE TITLE
Using Leaflet.Path.Transform Plugin with ngx-leaflet

### ISSUE THREAD

**Issue by riscie** [bluehalo/ngx-leaflet#87]
Hey there!

Great work you are putting into this! It's very appreciated!

I wanted to ask if somone can give me some directions on how I would be able to use the [Leaflet.Path.Transform](https://github.com/w8r/Leaflet.Path.Transform) plugin together with ngx-leaflet.

I know from the readme, that I can get a reference to the L.Map instance. However, the Leaflet.Path.Transform extends the functionality for the Polyline type (Polyline_options in specific) to make it dragable and scalable. I am not sure how I would be able to extend this type provided by ngx-leaflet.

Any help is appreciated.

Kindly, Matthias

**Comment by reblace** [comment]
I've never used this specific plugin, but I suspect all you'd need to do is get your build system (SystemJS/Webpack/ngCLI) to load the library into all scoped instances of Leaflet and then you should be able to use it. This library looks like it just alters the behavior of existing Leaflet types.

**Comment by riscie** [comment]
Thank you. I will have a closer look into this soon and post my findings here.

**Comment by reblace** [comment]
I'll probably take a crack at getting this to work soon. In the interim, I've started a repo that will eventually have several examples of how to get third-party libraries to work with ngx-leaflet: https://github.com/Asymmetrik/ngx-leaflet-tutorial-3rd-party-libs

**Comment by reblace** [comment]
Update: See the above repo for a working example in the "Leaflet.Path.Transform" subdirectory.

**Comment by riscie** [comment]
Wow thank you so much @reblace! This is a big help for me!

**Comment by reblace** [comment]
I'm gonna close this, feel free to post another issue if you run into any problems. Thanks!
