### ISSUE TITLE
How to use pixel dimensions instead of latLng

### ISSUE THREAD

**Issue by razfazz** [bluehalo/ngx-leaflet#90]
I wrote a tileserver which serves a huge image in tiles in different zoom levels.
I is possible switch leaflet to pixel mode in this plugin?

**Comment by AndreasSchmid1** [comment]
would be nice to access the containerPointToLatLng() method before onmapready to set it in the mapped latlng in the options

**Comment by reblace** [comment]
```containerPointToLatLng()``` hangs off of the map object, right?

The onMapReady function is called immediately after the map object is instantiated, so presumably you could call that method and then bind to the ```layers``` array.

I'm not really familiar with "pixel mode", so if you could give me an example of how you would make it work independent of the plugin, I could probably show you how to make it work with the plugin.

**Comment by razfazz** [comment]
I think the onMapReady and the map.unproject method was exactly what i wanted. Plus we need to set CRS.Simple

**Comment by reblace** [comment]
Ok, I'm gonna close this as resolved. If you have other issues, feel free to open another issue.

**Comment by razfazz** [comment]
Ok yes. I think it can be closed after map project and unproject does the transformation. 
But I was not able to set  crs: L.CRS.Simple described in http://leafletjs.com/examples/crs-simple/crs-simple.html. 
Is there a way to do it with your plugin?

**Comment by mcurtis22** [comment]
You can set the CRS in the leafletOptions object that is passed to the directive.

**Comment by PixelPerfectJenna** [comment]
@razfazz Were you able to set the map to pixel mode and then define the map bounds?
