### ISSUE TITLE
Angular4 Typescript SystemJS Integration Problem

### ISSUE THREAD

**Issue by Boud** [bluehalo/ngx-leaflet#92]
Hello,

I tried installing your component following the documentation steps. 
Did the three npm installs:
`npm install leaflet
 npm install @asymmetrik/ngx-leaflet
npm install @types/leaflet`

After importing the module in the app module I get the following error : 
`node_modules/@asymmetrik/ngx-leaflet/dist/leaflet/core/leafl‌​et.directive.d.ts (2,37): Module '"leaflet"' has no exported member 'MapOptions' `

I tried editing the leafl‌​et.directive.d.ts changing the options attribute to :any just to see if it would work but I got other errors afterwards

Is there a specific step I'm missing ? Or a specific Angular Version to use ?
I'm using Angular 4.2.5 with AOT but no webpack

**Comment by reblace** [comment]
```@types/leaflet``` is listing 0.7.x as their latest version. You'll need to manually override it to be v1.x.

See https://github.com/Asymmetrik/ngx-leaflet/issues/91 for more details and for how to fix it.

**Comment by Boud** [comment]
Thanks a lot for your quick response. 

For @types/leaflet I was getting the 1.2.1 version then changed it to 1.2.0 so with AOT no more problems

However were are using SystemJS in the project (for dev environnements) and I can't manage to get the plugin to work.

Do you have a setup in that case ? I couldn't find anything in the documentation.

In the system.js config file I have added the following : 


- In the map section  `'@asymmetrik/ngx-leaflet': 'node_modules/@asymmetrik/ngx-leaflet'`

- In the packages section ` '@asymmetrik/ngx-leaflet': { main: 'dist/index.js , defaultExtension: 'js'}`

I get the following error 

> Unable to dynamically transpile ES module
>    A loader plugin needs to be configured via `SystemJS.config({ transpiler: 'transpiler-module' })`.
> 

Do I need to setup a specific transpiler with systemJS ?

Thanks in advance !

**Comment by Boud** [comment]
I also tried using the bundle in map section

`  '@asymmetrik/ngx-leaflet': 'node_modules/@asymmetrik/ngx-leaflet/dist/bundles/'`

and package section

` '@asymmetrik/ngx-leaflet': { main: 'ngx-leaflet.js', defaultExtension: 'js'}`

 but It didn't work either (doesn't find the leaflet directive)

**Comment by Boud** [comment]
Nevermind I'm an idiot !

I need also to add the leaflet import to the systemjs config !
