### ISSUE TITLE
Error while ng build with AOT

### ISSUE THREAD

**Issue by Jagpreet16** [bluehalo/ngx-leaflet#93]
Hi,

I am using ngx-leaflet and it builds up somehow when I dont using AOT flag. But as soon as I use AOT flag it is showing me this error.

My module file:

```
import { LeafletModule } from '@asymmetrik/ngx-leaflet';
...

@Pipe({ name: 'safeHtml' })
export class SafeHtmlPipe implements PipeTransform {
    constructor(private sanitized: DomSanitizer) { }
    transform(value) {
        return this.sanitized.bypassSecurityTrustHtml(value);
    }
}

@NgModule({
    ...
    imports: [
       ...,
        LeafletModule.forRoot()
    ],
...
})

export class TaskModule { }
```

> ERROR in Error encountered resolving symbol values statically. Could not resolve @asymmetrik/ngx-leaflet relative to /builds/vernuso/trust/src/app/task/task.module.ts., resolving symbol TaskModule in /builds/vernuso/trust/src/app/task/task.module.ts, resolving symbol TaskModule in /builds/vernuso/trust/src/app/task/task.module.ts, resolving symbol TaskModule in /builds/vernuso/trust/src/app/task/task.module.ts
> 
> ERROR in multi ./src/styles.css ./src/css/mapping.css ./~/quill/dist/quill.core.css ./~/quill/dist/quill.snow.css ./~/leaflet/dist/leaflet.css
> Module not found: Error: Can't resolve '/builds/vernuso/trust/node_modules/leaflet/dist/leaflet.css' in '/builds/vernuso/trust'
>  @ multi ./src/styles.css ./src/css/mapping.css ./~/quill/dist/quill.core.css ./~/quill/dist/quill.snow.css ./~/leaflet/dist/leaflet.css

Am I missing anything here? Please help.

**Comment by reblace** [comment]
Are you using ng cli? Can you share some more code from the project? If I had to guess, maybe there's an issue with the tsconfig for your aot build?

**Comment by Jagpreet16** [comment]
Yes, I am using cli. Below is the packages.json
```

"dependencies": {
    "@agm/core": "^1.0.0-beta.1",
    "@angular/common": "^2.3.1",
    "@angular/compiler": "^2.3.1",
    "@angular/core": "^2.3.1",
    "@angular/flex-layout": "^2.0.0-rc.1",
    "@angular/forms": "^2.3.1",
    "@an
```gular/http": "^2.3.1",
    "@angular/material": "^2.0.0-beta.2",
    "@angular/platform-browser": "^2.3.1",
    "@angular/platform-browser-dynamic": "^2.3.1",
    "@angular/router": "^3.3.1",
    "@angular2-material/core": "^2.0.0-alpha.7-4",
    "@asymmetrik/ngx-leaflet": "^2.5.1",
    "@types/leaflet": "^1.2.0",
    "leaflet": "^1.2.0",
  },

and tsconfig.json
```

{
  "compilerOptions": {
    "baseUrl": "",
    "declaration": false,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "lib": ["es6", "dom"],
    "mapRoot": "./",
    "module": "es6",
    "moduleResolution": "node",
    "outDir": "../dist/out-tsc",
    "sourceMap": true,
    "target": "es5",
    "typeRoots": [
      "../node_modules/@types"
    ]
  }
}

```

**Comment by reblace** [comment]
I can't reproduce this. But, I have an example ng cli project that I'm building for a tutorial I'm writing on how to use this plugin. You can find the repo here: https://github.com/Asymmetrik/ngx-leaflet-tutorial-ngcli

You could compare your setup to mine and see where they diverge. That might help you track down your issue.

The error output you're seeing might be related

**Comment by Jagpreet16** [comment]
I can see you are using angular 4. Is this the requirement? I am using angular 2.3

Please suggest.

**Comment by reblace** [comment]
I don't think I'm doing anything ng4 specific. More specifically, I don't think I changed anything when I went from 2.x to 4. You could try changing the github project I referenced with ng 2.x and see if it works.

**Comment by reblace** [comment]
Did you get anywhere with this? I just tested the tutorial with ng2 and it seems fine

**Comment by reblace** [comment]
Gonna close this cause I haven't heard anything in a while. Let me know if there are any specific issues that you encounter with AOT.
