### ISSUE TITLE
leafletOptions are ignored inside async code 

### ISSUE THREAD

**Issue by AndreasSchmid1** [bluehalo/ngx-leaflet#95]
```
const test = await callasync function 

// this will get ignored...

   this.options = {
            layers: [
              tileLayer(this.requestTileUrl, { maxZoom: 11, attribution: '...', accessToken: 'your.mapbox.access.token' })
            ],
            zoom: 3,
          
            center: latLng(0, 0),
          }; 
```
Is there any way to delay the onMapReady event? I need to request basic map configurations via http get before I finally load the map

**Comment by reblace** [comment]
The options input binding is only used when the map is initialized, so changes won't be applied if you modify it after the map is initialized. In other words, you can't set the options asynchronously. You should use the ```leafletOptions``` input binding to set default and/or static options that are known/defined when your component is defined, and then use the other input bindings for anything that needs to be async or dynamic.

Leaflet doesn't require any layers to create the map, but it does require an initial zoom/center. So for your use case, I would recommend you set a default zoom/center in the options and then bind an array to the ```leafletLayers``` input binding. Your asynchronous code can modify the layers array, and the changes will be detected and applied by the ngx-leaflet plugin.

```
<div leaflet style="height: 400px;"
        [leafletOptions]="options"
        [leafletLayers]="layers">
</div>
```

```
// Initialize the options
options = { zoom: 3, center: latLng(0, 0) };

// Initialize layers to empty array
layers: [];

ngOnInit() {
    // Get layers asynchronously
    this.loadLayers((layers: Layer[]) => { this.layers = layers; } );
}
```

I didn't check the syntax of this example, but the basic idea should work.

**Comment by AndreasSchmid1** [comment]
thank you @reblace . I solved it temporary with a *ngIf="showContent" tag but your solution makes more sense

**Comment by reblace** [comment]
Let me know if you have any issues with the way I suggested, thanks!

**Comment by andreagosto** [comment]
Hi @reblace, so, how can i recenter the map programmatically?

**Comment by reblace** [comment]
There's an example in here: https://github.com/Asymmetrik/ngx-leaflet/tree/master/src/demo/app/leaflet/core

You can input bind to 'leafletCenter'

**Comment by XardasLord** [comment]
fyi @reblace 
Hello, I'm getting this error when trying to use Layers[] value asynchronously like this :
```
<div id="map-container"leaflet[leafletOptions]="options" [leafletLayers]="(mapLayers$ | async)!"></div>
```
or even subscribing in a code like this:
```
<div id="map-container"leaflet[leafletOptions]="options" [leafletLayers]="mapLayers"></div>

this.store.select(MapsState.getMapLayers).subscribe(result => {
      this.mapLayers = result;
    });
```

The message error is always the same:
```
ERROR TypeError: Cannot add property _leaflet_id, object is not extensible
    at stamp (leaflet-src.js:69:23)
    at NewClass.addLayer (leaflet-src.js:6893:14)
    at asymmetrik-ngx-leaflet.mjs:496:29
    at DefaultIterableDiffer.forEachAddedItem (core.mjs:28787:13)
    at asymmetrik-ngx-leaflet.mjs:495:29
    at _ZoneDelegate.invoke (zone.js:375:26)
    at Zone.run (zone.js:134:43)
    at NgZone.runOutsideAngular (core.mjs:26496:28)
    at LeafletLayersDirective.updateLayers (asymmetrik-ngx-leaflet.mjs:491:27)
    at LeafletLayersDirective.ngOnInit (asymmetrik-ngx-leaflet.mjs:474:14)
```

What I try to achieve is to use those options asynchronously (from external sources).

**Comment by neuged** [comment]
@XardasLord  or anybody who stumbles into this error as I did myself: This is  probably due to ngrx – or whatever else you use for `this.store` – not wanting you to extend objects, that are directly from the store. You probably need to have only the configuration etc. in the store and change/construct the layers on change.

For example if your layers are a bunch of Markers, this would display them without the above error (by creating new markers):

```typescript
import {marker} from 'leaflet';

this.store.select(MapsState.getMapLayers).subscribe(result => {
    this.mapLayers = result.map((m) => marker(m.getLatLng(), m.options);
});
```
