### ISSUE TITLE
How to change the unload tiles strategy

### ISSUE THREAD

**Issue by tvfire** [bluehalo/ngx-leaflet#96]
I am suffering issues when zooming into a map that the tiles from the previous zoomlevel are unloaded before the tiles from the next zoomlevel are loaded. This causes unattractive flickering and zoom experience. Is it somehow possible to wait or delay the tiles unloading?

**Comment by reblace** [comment]
This wouldn't be managed by the ngx-leaflet plugin. You'd need to go see if there are options in <a href="leafletjs.com">Leaflet</a> itself that allow this behavior. Generally, tiles are supposed to be zoomed in and then the new tiles loaded. It's possible that a poor connection or slow tile server may delay the loading of the new tiles, causing the gap/flickering you're describing.

**Comment by reblace** [comment]
Closing as addressed, unless there are other issues specific to the plugin. Thanks!
