### ISSUE TITLE
Styling divIcon

### ISSUE THREAD

**Issue by alexgoldstone** [bluehalo/ngx-leaflet#99]
I have the basics of ngx-leaflet up and running and am able to display markers.

I want to display a label alongside my markers so have tried to use `divIcon`.

The content of my divIcon HTML displays fine but I don't seem to be able to style it using the component's scss file.

My icon definition looks like:
```
labelIcon = divIcon({
    className: 'example',
    html: '<img src="/assets/marker-icon.png"><span>TESTING</span>'
});
```

My usage of the divIcon is identical to regular markers:
```
const anotherMarker = marker(
    [46.879966 + 0.1 * (Math.random() - 0.5), -121.726909 + 0.1 * (Math.random() - 0.5)],
    { icon: this.labelIcon }
);
```

The SCSS I am trying to use for testing is:
```
:host {
    .leaflet-container .leaflet-marker-icon.example span {
        display: block;
        margin-left: 30px;
        margin-top: -30px;
        font-size: 24px;
        color: #00f;
    }
}
```

I have also tried dropping the `:host` and tried prefixing the css block with `::ng-deep` but cannot find a combination that causes any styling to be applied.

I am presumably missing something obviously but will be grateful for any guidance you can provide.

**Comment by alexgoldstone** [comment]
Apparently I missed a combination, for future reference to maybe aid others, this works:
```
:host {
    ::ng-deep .leaflet-marker-icon.example span {
        display: block;
        margin-left: 30px;
        margin-top: -30px;
        font-size: 24px;
        color: #00f;
    }
}
```

::ng-deep is deprecated but there does not seem to be an alternative at present.

**Comment by reblace** [comment]
You probably already found this, but here's the ngx docs for this: https://angular.io/guide/component-styles

I've run into issues using Leaflet with emulated view encapsulation specific to shadow piercing descendant styling. Admittedly, I haven't really dug into it enough to find the "right" solution. Usually, I just set the component viewEncapsulation to none and use css classes applied to my component to mimic encapsulation.
